### ISSUE TITLE
old kernel version

### ISSUE THREAD

**Issue by bgkillas** [void-linux/void-mklive#101]
void installer installs linux 5.3.18 instead of linux 5.4.5 and https://www.kernel.org/ says 5.3.18 is at its eol

**Comment by Duncaen** [comment]
You can install other kernel series with xbps.

https://docs.voidlinux.org/config/kernel.html

> The linux meta package which is installed by default depends on one of the kernel packages, usually the latest mainline kernel that works with all dkms modules.

**Comment by bgkillas** [comment]
ik but shouldent it be by default now that 5.3.18 is eol

**Comment by Duncaen** [comment]
It is EOL since 3 days, as I said you can always install newer series and pushing a kernel that breaks users dkms modules is worse than having a default kernel that is EOL for some days.
Void Linux prefers to not break things instead of rolling with the absolutely latest possible.
