### ISSUE TITLE
Can't connect to Wi-Fi because firmware is missing

### ISSUE THREAD

**Issue by goleo108** [void-linux/void-mklive#102]
I use RTL8188EE and MT7601 Wi-Fi adapters and I can't connect to Wi-Fi because both /usr/lib/firmware/rtlwifi/rtl8188efw.bin and /usr/lib/firmware/mt7601u.bin are missing. They both are provided by linux-firmware package and I don't know why you don't include it in the live system.

**Comment by xtraeme** [comment]
I agree. Linux-firmware should be part of live image.

**Comment by xtraeme** [comment]
I just checked, linux-firmware is already a dependency of linux, so that all live images depend on it.
