### ISSUE TITLE
swap UUID not set in fstab

### ISSUE THREAD

**Issue by bsduck** [void-linux/void-mklive#107]
Hello,
I made an install using the new ISO, after which the installed system would not boot properly because the swap UUID was missing in fstab. Using the previous ISO from 2018 it works fine.

**Comment by xtraeme** [comment]
this could be a regression... I haven't looked at the void-mklive for a long while...

**Comment by classabbyamp** [comment]
cannot reproduce on a more recent image using either local or network install
