### ISSUE TITLE
Can we get a Void Linux Docker Image from this?

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-mklive#114]
I would like to start building docker images with this rather than alpine. Can we get a docker image of this so that users can run
"From void
..."

in a docker file? That would be sweet.

**Comment by Frick-David** [comment]
or is the image
From voidlinux/voidlinux-musl ? Just saw this. I will add some documentation to the wikis for others if so if I may and can get confirmation on this?

**Comment by the-maldridge** [comment]
https://hub.docker.com/u/voidlinux is the official docker account.  You can `FROM voidlinux/voidlinux` for glibc or `FROM voidlinux/voidlinux-musl` for musl.

**Comment by Frick-David** [comment]
Does the average user have the ability to edit the wiki. I will add this to the docker page

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by the-maldridge** [comment]
The wiki is deprecated.  Send a PR to void-docs instead.

**Comment by Frick-David** [comment]
Thanks a lot.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
