### ISSUE TITLE
Pinephone Support

### ISSUE THREAD

**Issue by EliteTK** [void-linux/void-mklive#119]
I've been working on supporting the Pinephone. I can already build a working image.

Similarly to the PBP issue, this one exists to track my progress on this and to bring attention to it so that anyone else wishing to get voidlinux working on the pinephone can re-use my existing work.

- [x] Voidlinux builds and runs
- [ ] Package templates
  - [x] Uploaded to public [repo](https://github.com/EliteTK/void-packages/tree/pinephone) \*
  - [ ] Conform to contributing standards
  - [ ] Merged
- [ ] void-mklive
  - [x] Uploaded to public [repo](https://github.com/EliteTK/void-mklive/tree/pinephone) \*
  - [ ] Merged

\* Note: I am going to push -f to these branches. Just so everyone is aware ahead of time.

I have some questions which I don't know the answers to:

- Where do I get the config file for the bluetooth firmware for the pinephone? The source for the firmware has a file for the pinebookpro but nothing for the pinephone.
- Does CC need to be exported for makefiles which rely on it? cc is not a symlink when I try to build which is odd to me. The pinebookpro u-boot package doesn't set CC and supposedly builds so I'm confused why my u-boot would need this.
- The pinebookpro u-boot package doesn't flash the u-boot either as a kernel config hook or as some kind of postinstall, how should this be handled?
  > Flashing is done by mkimage when the image is built. u-boot images are installed to /boot, so they have to be flashed manually after upgrades. To make it easier, I think we should just provide some tool to flash them to correct place (analagous to grub-install) and document it's use. Updates to u-boot images are not very frequent anyway.
- The pinebookpro mkimage does an xbps-reconfigure in the chroot as part of the image making process to re-generate the u-boot boot.scr but it looks like this already happens in mkplatformfs.sh, is this necessary?
  > Partition UUIDs are only known on mkimage step, so reconfigure is needed to update configuration with correct UUIDs.

Feel free to report issues to the issue trackers in the respective repositories and I'll have a look at them, or just post comments here.

Contributions are welcome but I'm not sure if they won't have to be squashed. If people have suggestions it would be easier to just tell me what I should do and I'll credit the person in the commit message.

Footnote: Bear with me, I don't know what I'm doing, I'm not a maintainer.

**Comment by renatoaguiar** [comment]
@EliteTK Here are answers to some of your questions:

>     * The pinebookpro u-boot package doesn't flash the u-boot either as a kernel config hook or as some kind of postinstall, how should this be handled?

Flashing is done by mkimage when the image is built. u-boot images are installed to /boot, so they have to be flashed manually after upgrades. To make it easier, I think we should just provide some tool to flash them to correct place (analagous to grub-install) and document it's use. Updates to u-boot images are not very frequent anyway.

>     * The pinebookpro mkimage does an xbps-reconfigure in the chroot as part of the image making process to re-generate the u-boot boot.scr but it looks like this already happens in mkplatformfs.sh, is this necessary?

Partition UUIDs are only known on mkimage step, so reconfigure is needed to update configuration with correct UUIDs.

BTW, adding support for pinephone is on my personal todo list, so I'm willing to help with that.

**Comment by EliteTK** [comment]
> @EliteTK Here are answers to some of your questions:
> 
> > ```
> > * The pinebookpro u-boot package doesn't flash the u-boot either as a kernel config hook or as some kind of postinstall, how should this be handled?
> > ```
> 
> Flashing is done by mkimage when the image is built. u-boot images are installed to /boot, so they have to be flashed manually after upgrades. To make it easier, I think we should just provide some tool to flash them to correct place (analagous to grub-install) and document it's use. Updates to u-boot images are not very frequent anyway.
> 
> > ```
> > * The pinebookpro mkimage does an xbps-reconfigure in the chroot as part of the image making process to re-generate the u-boot boot.scr but it looks like this already happens in mkplatformfs.sh, is this necessary?
> > ```
> 
> Partition UUIDs are only known on mkimage step, so reconfigure is needed to update configuration with correct UUIDs.
> 
> BTW, adding support for pinephone is on my personal todo list, so I'm willing to help with that.

Thanks! I added your replies to the OP. I think my void-mklive only needs one small patch (chroot-cleanup after the reconfigure) now before it's ready for a PR.

**Comment by anjandev** [comment]
It would also be nice to have a ui packaged for the pinephone. My favorite and likely the easiest to package is sxmo: https://sr.ht/~mil/Sxmo/

**Comment by EliteTK** [comment]
@anjandev I saw that recently too and thought the same.

I had to take a bit of a break from this stuff as I was busy but now I think would be a good time for me to get back to this and get it finished off.

Pinephone software support has moved forward quite a bit in the time I’ve taken my break so it should be a lot easier to get things more polished.

**Comment by jjsullivan5196** [comment]
Hi everyone, I personally had an itch to get a well-supported KISS-style distro onto the pinephone, so I started working on support for it again.

A good deal has changed in the past few months, and I believe I've captured most of the work that's been done so far. Here's a shortlist for the important stuff:

- Added u-boot and devicetree support for hardware revisions 1.1 and 1.2
- Crust power management firmware is now stable, adds features like deep sleep and wake-on-modem. See [crust-firmware](https://github.com/crust-firmware/crust)
- Downstream stable kernel 5.8 that includes support for most of the hardware features in the pinephone (modem audio routing/power management, USB-C DisplayPort Alt Mode/Power Delivery/OTG, fast charging, etc) [More info](https://xnux.eu/devices/pine64-pinephone.html#toc-feature-driver-support-matrix)

So far I've built a new image using the changes @EliteTK already forked from [void-mklive](https://github.com/EliteTK/void-mklive/tree/pinephone), and u-boot runs/kernel boots with a working console. 

I still want to test some of the hardware features mentioned, so I'll only be opening a draft pull request with what I have right now. I'd still appreciate any review notes in the meanwhile, as I believe the bulk of the work to bring these features in is done already.

**Comment by jjsullivan5196** [comment]
A little more progress, tested USB-C connectivity on a HP lapdock and the important stuff appears to work. Looks like I can go buy a lotto ticket!

Video of it working here if you'd like to see https://drive.google.com/file/d/1-HjJd4wct4DrwBEz2X8DukFvlM4pQGFT/view

**Comment by EliteTK** [comment]
My apologies for dropping this, I really ran out of free time to work on it. It's good to see that you're picking it up @jjsullivan5196.

**Comment by jjsullivan5196** [comment]
@EliteTK it's no trouble, I was motivated to get good software on this device and I have too much free time. Also your patch for mklive really helped get me off the ground, thank you!

**Comment by jjsullivan5196** [comment]
I've patched @EliteTK's mklive to make it work with the pinephone PR https://github.com/jjsullivan5196/void-mklive/tree/pinephone just want to check a couple of things then I'll submit it for a PR against this repo.

**Comment by Frick-David** [comment]
Any chance someone can make some docs on how to use this for the pinephone? Would be super cool!

**Comment by justinmbrock** [comment]
I'd love to know the current status of this. I also came here thinking I'd port Void over to the PinePhone, since it wasn't on Pine64's list of OSes and I have zero interest in supporting ExpidusOS. I have no Idea what I'm doing, but I do have a lot of free time to figure it out, and I need to do something.

**Comment by paper42** [comment]
```sh
git clone https://github.com/void-linux/void-mklive
make
sudo ./mkrootfs.sh aarch64-musl
sudo ./mkplatformfs.sh pinephone void-aarch64-musl-ROOTFS-YYYYMMDD.tar.xz # replace aarch64-musl with aarch64 if you want the glibc version
```
then follow the guide in the handbook: https://docs.voidlinux.org/installation/guides/arm-devices/index.html
If you need a complete image and not just platformfs, generate it with:
```sh
sudo ./mkimage.sh void-pinephone-PLATFORMFS-YYYYMMDD.tar.xz
```

The mesa lima driver is required for graphical interfaces.

**Comment by the-maldridge** [comment]
The current status is that it works.  This is probably about as far as void will take it as to be a mobile OS, someone needs to put together  DE/DM combination and lots of other config, which is not what Void does.

**Comment by justinmbrock** [comment]
Hey, that's awesome! Thanks for the answers. I'll see what I can do. If anyone on the thread wants to maybe work on it too, hit me up. This is exactly the kind of project I need to focus on 😀

**Comment by paper42** [comment]
> The current status is that it works. This is probably about as far as void will take it as to be a mobile OS, someone needs to put together DE/DM combination and lots of other config, which is not what Void does.

@the-maldridge can we close this issue then?

**Comment by darkralts** [comment]
bruh
