### ISSUE TITLE
Package 'intel-ucode' not found in repository pool.

### ISSUE THREAD

**Issue by svenper** [void-linux/void-mklive#121]
Passing other extra packages with `-p` like `grub-x86_64-efi` or `gptfdisk` do not crash like this.

This package `intel-ucode` used to work before.

```text
$ sudo ./mklive.sh -a x86_64-musl -r https://repo.voidlinux.eu/current/musl -p "void-repo-nonfree intel-ucode"
...
squashfs-tools-4.4_1: configuring ...
squashfs-tools-4.4_1: installed successfully.
bzip2-1.0.8_1: configuring ...
bzip2-1.0.8_1: installed successfully.
xorriso-1.5.3_1: configuring ...
xorriso-1.5.3_1: installed successfully.

37 downloaded, 37 installed, 0 updated, 37 configured, 0 removed.
[3/9] Installing void pkgs into the rootfs: base-system void-repo-nonfree intel-ucode ...
Package 'intel-ucode' not found in repository pool.
ERROR: Missing required binary packages, exiting...
```

**Comment by the-maldridge** [comment]
You're trying to both install a new repo configuration and use it in the same transaction.  XBPS cannot do this.  Right now I'm not aware of a good solution, and you may have to edit the generated mklive.sh script to be able to do this in two passes.

**Comment by the-maldridge** [comment]
An alternative of course would be specifying the nonfree repo as an argument to the command, which would cause it to be updated in a separate transaction, and you could subsequently install intel-ucode.

**Comment by svenper** [comment]
Thanks for the explanation! Replacing the repo urls solved it:

<pre>sudo ./mklive.sh -a x86_64-musl <b>-r https://alpha.de.repo.voidlinux.org/current/musl -r https://alpha.de.repo.voidlinux.org/current/musl/nonfree</b> -p "intel-ucode"</pre>
