### ISSUE TITLE
Reserved space on ISOs too small.

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-mklive#122]
It seems that at least for some of the ISOs with desktop environment there is not enough free space, inodes, whatever to make `build-live-images.sh` create usable output.
Here's a screenshot of trying to boot a `void-live-x86_64-20200404-gnome.iso` in qemu.
![qemu-void-live-x86_64-20200404-gnome](https://user-images.githubusercontent.com/10061347/78499246-cd608d00-774f-11ea-8466-0f34993074c6.png)
Here's the last lines of `/run/initramfs/rdsosreport.log`:
![qemu-void-live-x86_64-20200404-gnome-2](https://user-images.githubusercontent.com/10061347/78499402-c423f000-7750-11ea-9289-635a3365587d.png)

**Comment by xtraeme** [comment]
hmmm

**Comment by xtraeme** [comment]
need to think about it

**Comment by classabbyamp** [comment]
haven't run into this in my testing
