### ISSUE TITLE
installer.sh.in test_network()

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-mklive#123]
The function [test_network()](https://github.com/void-linux/void-mklive/blob/31df80c3417dceccf823cfee7ab088337d1e521b/installer.sh.in#L816) fetches `https://a-hel-fi.m.voidlinux.org/live/xtraeme.asc`. I don't know how (in)valuable this key is as of now and whether, perhaps, it should be replaced with the ASCII armored public key of the [currently used signing key](http://alpha.de.repo.voidlinux.org/live/current/void_images.asc).

**Comment by classabbyamp** [comment]
replaced with `/current/otime` in a8f87aa5a95e9ea96ef37948271ec3de3c9d1212
