### ISSUE TITLE
mklive, xz mc zsh live enviroment.

### ISSUE THREAD

**Issue by hechos** [void-linux/void-mklive#124]
nevermind, guys finally fixed.

**Comment by herveq1** [comment]
Same behaviour as Martin, at least for xz.

Mklive install xz for dracut, use it and clean up rootfs to save space.

I modified the cleanup_rootfs() function to remove package only if the
package is not in ${PACKAGE_LIST}. This works for xz.

I hope the maintainer will have 2 minutes to update mklive.sh 
Thanks
Hervé

-- mklive.sh~  2020-08-10 11:20:24.532469111 +0200
+++ mklive.sh   2020-08-10 11:54:47.727474698 +0200
@@ -165,12 +165,22 @@
 }
 
 cleanup_rootfs() {
+    local NEED_REMOVE
     for f in ${INITRAMFS_PKGS}; do
         revdeps=$(xbps-query -r "$ROOTFS" -X $f)
         if [ -n "$revdeps" ]; then
             xbps-pkgdb -r "$ROOTFS" -m auto $f
         else
-            xbps-remove -r "$ROOTFS" -Ry ${f} >/dev/null 2>&1
+            NEED_REMOVE=1
+            for xf in ${PACKAGE_LIST}; do
+               if [ $xf = $f ]; then
+                  NEED_REMOVE=0
+               fi
+            done
+            if [ $NEED_REMOVE -gt 0 ]; then
+               xbps-remove -r "$ROOTFS" -Ry ${f} >/dev/null 2>&1
+               echo "HQ remove  $f\n"
+            fi
         fi
     done
     rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01vmklive

**Comment by ericonr** [comment]
@herveq1 Can you make a PR for this?
