### ISSUE TITLE
Default kernel is still installed even when -v is specified

### ISSUE THREAD

**Issue by paper42** [void-linux/void-mklive#128]
When I specify I want linux5.6 using the `-v` option, everything works as expected, but the default 5.4 kernel is still downloaded and installed. 5.4's headers are installed too, but 5.6's are not.

**Comment by Noah-Huppert** [comment]
I added the `-v` option so I can try and tackle this.

I also noticed the default kernel stays installed, been meaning to fix this for a bit.

> 5.4's headers are installed too, but 5.6's are not.
Do you think specifying `-v linux5.6` should installed 5.6 headers? I suppose it should if 5.4 headers are installed by default.

**Comment by abenson** [comment]
5.4 headers shouldn't be installed by default. the default kernel stays because it's still pulled by base-system or whatever. not sure what pulls linux5.4-headers, but I assume something pulls linux-headers (dkms maybe?)

**Comment by Noah-Huppert** [comment]
Hmm, I might have to think about this. Bc ideally specifying `-v linux5.6` would install linux 5.6 then packages would install afterward. So if something like dkms requires linux headers it would grab linux5.6 headers not linux5.4 headers. 

The "ignore a package" option which was discussed in a recent "alternate kernels" reddit thread comes to mind here. Maybe if you specify a custom kernel version it should install base-system, ignoring the linux package. Then install your custom version. I'll have to actually check about the "ignore a package" option to ensure that does what I want / I understand it correctly.
