### ISSUE TITLE
void-installer static network problem?

### ISSUE THREAD

**Issue by dazoe** [void-linux/void-mklive#132]
when using void-installer and using static network setting it seems like the gateway doesn't get set properly. I traced it down to this line in the installer https://github.com/void-linux/void-mklive/blob/95e305c4611705838d35773ac6404caa80b40400/installer.sh.in#L927
shouldn't that be
`ip route add default via $gw`

**Comment by the-maldridge** [comment]
Technically it can be either.  In the case that is shown in the file, it is instructing the kernel to spew packets from that interface.  It is assumed that the layer 2 network will know what to do with them.  In some cases, this is not the right thing to do, and I suspect you may have found one of these cases.

**Comment by dazoe** [comment]
the command `ip route add <address> dev <device>` will instruct the kernel to send packets addressed to <address> down the <device> dev. it is very different from the command `ip add default via <address>` which tells the kernel to send packets to <address> when it cant find a matching route.

**Comment by classabbyamp** [comment]
284be34a1fccba4112aaaa3eed534fe9a4057dc1
