### ISSUE TITLE
Enable getty autologin by default

### ISSUE THREAD

**Issue by jepotter1-archive** [void-linux/void-mklive#137]
- All other distributions with command-line installers (Arch, Gentoo, and Alpine) log in automatically by default.
- The username and password are already hardcoded, so there is no possible use case for not wanting to login in automatically given that the username and password are already known in all circumstances.
- All of the GUI display managers are hardcoded to automatically login, yet getty is not.

**Comment by jwinnie** [comment]
<details>
<summary>Proposed patch</summary>

```
diff --git a/grub/grub_void.cfg.in b/grub/grub_void.cfg.in
index a2cda85..2d9ce8b 100644
--- a/grub/grub_void.cfg.in
+++ b/grub/grub_void.cfg.in
@@ -31,7 +31,7 @@ if [ cpuid -l ]; then
                root=live:CDLABEL=VOID_LIVE ro init=/sbin/init \
                rd.luks=0 rd.md=0 rd.dm=0 loglevel=4 gpt add_efi_memmap \
                vconsole.unicode=1 vconsole.keymap=@@KEYMAP@@ \
-               locale.LANG=@@LOCALE@@ @@BOOT_CMDLINE@@
+               locale.LANG=@@LOCALE@@ live.autologin @@BOOT_CMDLINE@@
         initrd (${voidlive})/boot/initrd
     }
     menuentry "@@BOOT_TITLE@@ @@KERNVER@@ (@@ARCH@@) (RAM)" {
@@ -40,7 +40,7 @@ if [ cpuid -l ]; then
                root=live:CDLABEL=VOID_LIVE ro init=/sbin/init \
                rd.luks=0 rd.md=0 rd.dm=0 loglevel=4 gpt add_efi_memmap \
                vconsole.unicode=1 vconsole.keymap=@@KEYMAP@@ \
-               locale.LANG=@@LOCALE@@ @@BOOT_CMDLINE@@ rd.live.ram
+               locale.LANG=@@LOCALE@@ live.autologin @@BOOT_CMDLINE@@ rd.live.ram
         initrd (${voidlive})/boot/initrd
     }
 fi
diff --git a/isolinux/isolinux.cfg.in b/isolinux/isolinux.cfg.in
index 69de967..3ff6db9 100644
--- a/isolinux/isolinux.cfg.in
+++ b/isolinux/isolinux.cfg.in
@@ -23,11 +23,11 @@ MENU COLOR sel          * #ffffffff #FF5255FF *
 LABEL linux
 MENU LABEL @@BOOT_TITLE@@ @@KERNVER@@ @@ARCH@@
 KERNEL /boot/vmlinuz
-APPEND initrd=/boot/initrd root=live:CDLABEL=VOID_LIVE init=/sbin/init ro rd.luks=0 rd.md=0 rd.dm=0 loglevel=4 vconsole.unicode=1 vconsole.keymap=@@KEYMAP@@ locale.LANG=@@LOCALE@@ @@BOOT_CMDLINE@@
+APPEND initrd=/boot/initrd root=live:CDLABEL=VOID_LIVE init=/sbin/init ro rd.luks=0 rd.md=0 rd.dm=0 loglevel=4 vconsole.unicode=1 vconsole.keymap=@@KEYMAP@@ locale.LANG=@@LOCALE@@ live.autologin @@BOOT_CMDLINE@@
 LABEL linuxram
 MENU LABEL @@BOOT_TITLE@@ @@KERNVER@@ @@ARCH@@ (RAM)
 KERNEL /boot/vmlinuz
-APPEND initrd=/boot/initrd root=live:CDLABEL=VOID_LIVE init=/sbin/init ro rd.luks=0 rd.md=0 rd.dm=0 loglevel=4 vconsole.unicode=1 vconsole.keymap=@@KEYMAP@@ locale.LANG=@@LOCALE@@ @@BOOT_CMDLINE@@ rd.live.ram
+APPEND initrd=/boot/initrd root=live:CDLABEL=VOID_LIVE init=/sbin/init ro rd.luks=0 rd.md=0 rd.dm=0 loglevel=4 vconsole.unicode=1 vconsole.keymap=@@KEYMAP@@ locale.LANG=@@LOCALE@@ live.autologin @@BOOT_CMDLINE@@ rd.live.ram
 LABEL c
 MENU LABEL Boot first HD found by BIOS
 COM32 chain.c32
```

</details>

**Comment by ericonr** [comment]
Does this work fine with a local install, which copies most of the files into the target device?

**Comment by jwinnie** [comment]
What do you mean by that? Isn't this supposed to be about the live image, so it has nothing to do with the installation? Pardon me, I don't know that much about operating system development.

**Comment by ericonr** [comment]
If you do a local install using the installer in the live image, it basically copies the live system into the target one. So if this change affects any files in the live image, it could be an issue. Taking a better look at your patch, I don't think it does, so it should be fine.

**Comment by the-maldridge** [comment]
I am not in favor of this patch.  Void does not chase the pack, so it is of no consequence that other distros log in automatically.

**Comment by jwinnie** [comment]
@the-maldridge It's more convenient, why not?

**Comment by bobertlo** [comment]
The only distros I've used that login automatically go straight to the installer program, but void basically has first class support for self guidef manual installation. In this light I don't find it at all odd that there is a login prompt.

I also agree that it doesn't matter what other distros do.

**Comment by jwinnie** [comment]
@bobertlo It's not odd, it's perfectly fine the way it is currently. But autologin would save a few keystrokes, that's all, and it's easy to implement.

**Comment by classabbyamp** [comment]
I think it's fair to say the general maintainer opinion is against this
