### ISSUE TITLE
mklive error: failed to find kernel package version

### ISSUE THREAD

**Issue by absolutelynothinghere** [void-linux/void-mklive#139]
I just installed Void and downloaded the mklive script. Whenever I run `sudo ./mklive.sh` the program dies on step one.

When updating repo data, the first repo generates a `transient resolver failure` error, the rest generate a `not found` error. Then, I get the message `xbps-uhelper: invalid option -- 'c'` and right underneath `ERROR: Failed to find kernel package version`.

Is this normal?

**Comment by ericonr** [comment]
That sounds like a DNS issue. Can the system connect to the internet otherwise?

**Comment by the-maldridge** [comment]
Yeah that's very much a dns fault, I suggest re-trying and it should succeed unless there's a fault somewhere in your network.

**Comment by absolutelynothinghere** [comment]
> That sounds like a DNS issue. Can the system connect to the internet otherwise?

Yes it can. I already used Firefox and installed software through `xbps-install` multiple times. A DNS issue may be responsible for the repo errors, but is it responsible for the kernel error?

> Yeah that's very much a dns fault, I suggest re-trying and it should succeed unless there's a fault somewhere in your network.

I retried a few times, the `not found` errors persist however the `transient` error sometimes goes away. The kernel error is still here unfortunately.

By the way thank you both for the quick reply 👍 I had a really good feeling about this distro and your care is one of the many green flags I've seen.

**Comment by ericonr** [comment]
>  I already used Firefox

Firefox does its own DNS nowadays iirc, but if `xbps-install` already worked, DNS should be fine, I guess.

> but is it responsible for the kernel error?

Due to connection errors the other steps might be missing some info. That's my guess, at least. You'd have to debug the script.

**Comment by absolutelynothinghere** [comment]
> Due to connection errors the other steps might be missing some info.

I think you're right... I re-ran mklive but specified the default repository again using `-r`, and also the architecture using `-a`, and got a working ISO! Let's hope mklive keeps working. ☺

Thank you all, I'm closing this issue for now. If I have questions in the future about the script (non-issues) who can ask?

**Comment by ericonr** [comment]
Probably better to go on #voidlinux on freenode IRC! The subreddit is a good place as well. If there are issues that you feel could be fixed by better documentation/code here, then open issues/PRs here. Take a look at infradocs.voidlinux.org for the complementary documentation.
