### ISSUE TITLE
rc.conf keyboard layout not working

### ISSUE THREAD

**Issue by tedbysek** [void-linux/void-mklive#162]
I am trying to do a custom chroot install of void on my laptop, and I want keyboard to be cz-qwertz however if I set keyboard layout as cz-qwertz (which I checked is valid layout) everytime I reboot after finished installation I get US layout in TTY. I don't really know if this is xbps or runit problem. I am installing Void from official live installer so I put it here.

**Comment by Duncaen** [comment]
I don't see how this could not work other than you editing the wrong or overwriting the file when doing the installation.

**Comment by tedbysek** [comment]
I don't know I just do
KEYMAP="cz-qwertz"
in rc.conf and runit doesn't seem to set it as intended

**Comment by Duncaen** [comment]
Which rc.conf?

**Comment by tedbysek** [comment]
/etc/rc.conf

**Comment by Duncaen** [comment]
Inside the chroot?

**Comment by tedbysek** [comment]
yes inside I even tried to change it after install

**Comment by classabbyamp** [comment]
do you still have this issue?

**Comment by tedbysek** [comment]
I stopped having this issue I do not really know what exactly changed
