### ISSUE TITLE
Include linux-headers in live image

### ISSUE THREAD

**Issue by ne9z** [void-linux/void-mklive#178]
Hi all, I'm writing [a Void Linux Root on ZFS installation guide](https://github.com/ne9z/openzfs-docs/blob/void-support/docs/Getting%20Started/Void%20Linux/Void%20Linux%20Root%20on%20ZFS.rst).

Currently, `linux-headers`, a package of a few MBs, is not included in the live images. This effectively makes building ZFS module impossible in the live environment:
- Live image released in 2019, shipped with kernel `5.3.9`
- `linux-headers` for `5.3.9` was removed from repo
- Installing any version of `linux-headers` requires a kernel upgrade, which is not possible in live environment
- `linux-headers` not installed, ZFS module can not be built

Therefore I would like to request the inclusion of `linux-headers` in live image, at least with `x86_64`.

**Comment by ne9z** [comment]
For example, [Artix Linux Live Image](https://github.com/ne9z/openzfs-docs/blob/arch-support/docs/Getting%20Started/Arch%20Linux/Artix%20Linux%20Root%20on%20ZFS.rst) ships with `linux-headers`, making ZFS in live environment much easier.

**Comment by Vaelatern** [comment]
Check out 2 resources:
https://github.com/void-linux/void-docs
https://github.com/leahneukirchen/hrmpf/

I consider this not a valid issue since what you ask is available, or readily built with options on existing code.
