### ISSUE TITLE
PinebookPRO black screen with newer mainline kernels

### ISSUE THREAD

**Issue by thypon** [void-linux/void-mklive#180]
Cc: @CameronNemo , @ericonr , @Johnnynator 

## What is happening?

- I build an image with latest kernel-5.10.2 and aarch64 root 

```
git clone https://github.com/void-linux/void-mklive
cd void-mklive
make
./mkrootfs.sh aarch64
./mkplatformfs.sh pinebookpro <base-tarballl>
./mkimage.sh -B 512M <rootfs-tarball>
```
- I flash the image to an SD `dd if=<image> of=<disk>`
- I try to boot the SD on Pinebook PRO
- The Screen Remains Black, the LED switch from yellow to green.

## Expected Behaviour

The system boots correctly

## Troubleshooting

I tried different microSD brands.
ARCH Linux image is booting correctly.

**Comment by CameronNemo** [comment]
I do not imagine you have a serial adapter for the PBP?

**Comment by thypon** [comment]
No serial adapter here with me. No change to the base image, not even the SD one is booting. When It is booting from the eMMC the led remains yellow, while on the SD it turns green. This usually means the kernel has booted.

**Comment by thypon** [comment]
@CameronNemo I think the title may be misleading, I'm not using a custom mainline kernel, I'm using the one included in void, pinebookpro-kernel.

The problem is that I cannot even create a working SD card from void-mklive with latest rootfs, at the moment.

**Comment by CameronNemo** [comment]
@thypon indeed the new kernel we have uses more modules it seems, conflicting with the initramfs-less image created by this repo. you could try to find out which Ms need to be Ys in the kernel config, or just add dracut to the platformfs.

**Comment by thypon** [comment]
I will try with dracut, thanks. It may be time to add dracut as pinebook-base package, anyway.

**Comment by thypon** [comment]
It's working good with dracut.

**Comment by ericonr** [comment]
I believe this has been fixed? Initramfs could be documented as a requirement, but that goes in void-docs.

**Comment by CameronNemo** [comment]
I would consider this fixed if building the image from this repo without any additional packages produced something functional. Right now the user has to manually specify dracut as an additional package. That is the bug from my POV.

**Comment by CameronNemo** [comment]
this can be closed now
