### ISSUE TITLE
Maybe installer could configure users from inside the chroot?

### ISSUE THREAD

**Issue by ElPresidentePoole** [void-linux/void-mklive#181]
When running void-installer, once you get to the Installation Source step (pictured below), if you choose Network the resulting install will not change the root's password and will not create the user specified in "UserAccount" (also pictured below).

![Installation Source](https://i.imgur.com/Mh5b7LV.png)

![UserAccount](https://i.imgur.com/4w9fzN7.png)

Here's the bug in action:

![Bug in action](https://i.imgur.com/x0zVu2K.png)

I think it might be time to update the live image.  I got bit reinstalling Void, and I don't think new users should have to chroot in to fix their freshly installed system.

**Comment by ericonr** [comment]
>I think it might be time to update the live image. 

Have you checked if this is working correctly for a freshly baked ISO?

**Comment by ElPresidentePoole** [comment]
> > I think it might be time to update the live image.
> 
> Have you checked if this is working correctly for a freshly baked ISO?

Yes, with a brand new iso it works as expected.

![](https://i.imgur.com/xyKUih6.png)

**Comment by ericonr** [comment]
Which ISOs have you tested? They are in the testing phase for now.

**Comment by ElPresidentePoole** [comment]
> Which ISOs have you tested? They are in the testing phase for now.

What do you mean?  I just made a new iso myself.

> void-live-x86_64-5.10.8_1-20210119.iso

**Comment by ericonr** [comment]
Yes, listed in https://alpha.de.repo.voidlinux.org/live/20201224/ 

They aren't all tested, though.

**Comment by ericonr** [comment]
The error message for this during installation https://www.reddit.com/r/voidlinux/comments/l2nwhk/error_during_installation_it_wont_create_an_user/

Likely caused by some mismatch with host PAM being older than the chroot PAM.

**Comment by ericonr** [comment]
I'm repurposing this issue to allow this to work in the long term, instead of requiring new images for weird breaking changes like these. If user configuration happens from inside the chroot, there won't be any version mismatch.
