### ISSUE TITLE
Missing linux headers

### ISSUE THREAD

**Issue by Boruch-Baum** [void-linux/void-mklive#185]
Hi. I'm new to void linux and am posting here because I don't see a support forum for the distribution.

The live xfce image runs linux 5.3.9_1 and does not include the linux headers for that version.

And, performing an update shows that the linux headers for that version are no longer available from the void package repository.

Consider my use-case: I want the live image to access (and possibly install into) an existing ZFS pool. I need to install zfs/dkms, but doing so can't update the proper kernel version because of lack of headers.

What does happen is that void installs headers for a different kernel version (5.10.11) and dkms operates on that.

This issue will affect any hot-plugging of kernel modules on the live media, right?

One solution would be to restore the 5.3.9 kernel and header to the void repository until you release new live-media, but that occurs to me to be better addressed to a support forum - which I can't find. That solution could help me (and possibly others) immediately.

A better solution is to always bundle kernel headers with the live media, but that won't help me immediately

**Comment by abenson** [comment]
There is an (unofficial) live image setup for ZFS, [hrmpf](https://github.com/leahneukirchen/hrmpf/releases).

**Comment by q66** [comment]
you are not supposed to install extra packages in the live iso anyway (as soon as it gets this old, partial upgrades may not be completely safe), so i'm afraid this is a wonfix

use hrmpf of build your own iso image with mklive with zfs built-in

**Comment by Boruch-Baum** [comment]
On 2021-01-27 09:18, Andrew Benson wrote:
>    There is an (unofficial) live image setup for ZFS, [1]hrmpf.

Got it. Thanks, but for the benefit of others (needing other kernel
modules) please don't close this issue until it's fixed, ie. return the
header package to the repo, or build new live images with the headers
included.

For me as a possible new user this brings up a bigger and more
important issue: where is the accumulated 'knowledge base' of void linux
users? I've found no forum, the existing wiki is outdated and sparse,
internet searches don't return useful results.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-01-27 09:20, Daniel Kolesa wrote:
>    you are not supposed to install extra packages in the live iso anyway
>    (as soon as it gets this old, partial upgrades may not be completely
>    safe), so i'm afraid this is a wonfix

That's off-base. The issue has nothing to do with extra packages. It's
an issue of a user needing kernel modules that weren't compiled into the
live-image's kernel. For that, you need dkms and kernel headers to add
the new kernel modules. The most common cases are hardware drivers that
weren't compiled into the kernel when built.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by the-maldridge** [comment]
This was closed as wontfix, as the functionality you have requested will not be implemented in new ISOs either.  If you wish to install with an exotic filesystem, hrmf is the stated way to do that, and if you want something more exotic you can always use mklive to build an ISO with whatever you want in it.

**Comment by ericonr** [comment]
>  For that, you need dkms and kernel headers to add the new kernel modules. The most common cases are hardware drivers that weren't compiled into the kernel when built.

This could be looked into in void-docs, we could orient users who require out-of-tree drivers (especially for network) to do a local install and then have instructions for downloading all packages needed to build DKMS modules on another device and transferring them over.

**Comment by Boruch-Baum** [comment]
On 2021-01-27 09:46, Érico Nogueira Rolim wrote:
>    This could be looked into in void-docs, we could orient users who
>    require out-of-tree drivers (especially for network) to do a local
>    install and then have instructions for downloading all packages needed
>    to build DKMS modules on another device and transferring them over.

That won't help without the linux-headers.

You either need to include the linux headers in the live-image (IMO, the
correct solution, but not an immediate fix) or keep the linux-headers
package in the repository for as long as you're offering an official
live image that boots that version of the kernel.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ericonr** [comment]
> That won't help without the linux-headers.

It would, since you could pull in a new kernel as well.

> keep the linux-headers
package in the repository for as long as you're offering an official
live image that boots that version of the kernel.

This isn't possible; repositories only hold the latest version of a package.

**Comment by Boruch-Baum** [comment]
Michael, I think you're missing the point. You seem to think that the
issue is 'exotic file systems' when it is 'kernel module compatibility'.
It will most often happen for hardware drivers, not filesystems.

If you only expect to release live images once every few years, they
either should be sufficiently self-contained to support unexpected
developments (ie. include the kernel headers), or the repository should
retain the header package for the kernel version of the official live image.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by q66** [comment]
we absolutely will not include ancient kernels back into the repository

we also will not include linux headers in the isos, since 1) the isos are already big enough as they are 2) just having linux headers will not help, you will need an entire development toolchain as well, which will lead to more bloating up 3) if you include only headers and not the toolchain and attempt to install the toolchain later, that may lead either to the toolchain not being installable, or to the resulting kernel modules having issues because of the compiler used to build the module being newer than the compiler used to build the kernel

**Comment by Boruch-Baum** [comment]
On 2021-01-27 09:58, Érico Nogueira Rolim wrote:
>      That won't help without the linux-headers.
>
>    It would, since you could pull in a new kernel as well.

??

You would need to reboot in order to use the 'new kernel' and its
headers, and doing so would lose everything because you're using a live
image! In short, for the purpose of a live-image, you're stuck with the
'old' kernel.

>      keep the linux-headers
>      package in the repository for as long as you're offering an official
>      live image that boots that version of the kernel.
>
>    This isn't possible; repositories only hold the latest version of a
>    package.

Not true. I'm looking at the repository now and see many kernel versions
being supported. See there "linux[0-9].[0-9]+-headers"

In fact, the repository still has 'ancient' linux headers from version
4.4 !!

It's only the version on the live image that has been 'skipped' and
deleted from the repository.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by q66** [comment]
we only support kernels that are supported by upstream, 4.4 is one of them: https://www.kernel.org/category/releases.html

**Comment by ericonr** [comment]
> You would need to reboot in order to use the 'new kernel' and its
headers, and doing so would lose everything because you're using a live
image! In short, for the purpose of a live-image, you're stuck with the
'old' kernel.

You missed the part where I suggested a local install, which doesn't need network drivers.

> Not true. I'm looking at the repository now and see many kernel versions
being supported. See there "linux[0-9].[0-9]+-headers"

linux4.4-4.4.253 is in the repositories, what do you do if the live ISO was built with linux4.4-4.4.252? That's the issue.

**Comment by Boruch-Baum** [comment]
On 2021-01-27 10:02, Daniel Kolesa wrote:
>    we absolutely will not include ancient kernels back into the repository

Putting aside void's admirable continuing support for linux4.x kernels,
you could just update the live image to use a recent LTS kernel.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ericonr** [comment]
Half the reason people ask for new ISOs is bleeding edge hardware support; using LTS doesn't solve that.

**Comment by Boruch-Baum** [comment]
On 2021-01-27 10:10, Érico Nogueira Rolim wrote:
>    You missed the part where I suggested a local install, which doesn't
>    need network drivers.

I don't think I missed that part. Even with a local install, the host
needs the support. Also, the issue need not be related to network
drivers, although that is a common example, it could be any hardware
component.

>    linux4.4-4.4.253 is in the repositories, what do you do if the live
>    ISO was built with linux4.4-4.4.252? That's the issue.

In a sense, yes, part of the issue is that the right-hand that build the live
ISO is doing so without coordinating with the left-hand that maintains
the repositories. Another way to frame it is that the live ISO isn't
being built with an LTS kernel version.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by q66** [comment]
the live iso is built with whatever is the current kernel at the time

kernel 4.3 was never LTS, and was removed when it became EOL, so it's gone

**Comment by Boruch-Baum** [comment]
On 2021-01-27 10:16, Érico Nogueira Rolim wrote:
>    Half the reason people ask for new ISOs is bleeding edge hardware
>    support; using LTS doesn't solve that.

Having the linux headers often DOES support that, and the context is the
current situation of the current void live ISO using a 5.3.9 kernel, at
this point older than several LTS kernels.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-01-27 10:19, Daniel Kolesa wrote:
>    kernel 5.3 was never LTS, and was removed when it became EOL, so it's
>    gone

Exactly. Now we're beginning to get on the same wave-length. That's why
I submitted this github issue.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by q66** [comment]
and the answer is "wontfix"; isos are regenerated when they are regenerated, and there is no need to include headers in them, if you want to compile kernel modules, make your own iso, use hrmpf, or grab one of the unofficial nightly isos and install headers yourself

there is no more discussion to be had, so i am locking the thread
