### ISSUE TITLE
USB broken with kernel 4.18.9 on the latest ISO

### ISSUE THREAD

**Issue by ghost** [void-linux/void-mklive#19]
Just downloaded one of the new ISOs released in:
https://vm1.a-lej-de.m.voidlinux.org/live/20180921/

Unfortunately, we are victims of this nasty bug:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1629323.html

:angry: can't boot from USB.

---

````
# lspci |grep USB
00:1a.0 USB controller: Intel Corporation 5 Series/3400 Series Chipset USB2 Enhanced Host Controller (rev 05)
00:1d.0 USB controller: Intel Corporation 5 Series/3400 Series Chipset USB2 Enhanced Host Controller (rev 05)

# lsusb
Bus 002 Device 003: ID 0408:03f1 Quanta Computer, Inc. 
Bus 002 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

# lsmod |grep ehci
ehci_pci               16384  0
ehci_hcd               86016  1 ehci_pci
usbcore               249856  4 ehci_pci,usb_storage,ehci_hcd,uas
````

**Comment by Piraty** [comment]
Interesting. I played with `4.19rc{2,3,4}` in my own live isos last week and didn't encounter this issue.

**Comment by cr6git** [comment]
:tada: it's fixed in 4.18.10.

**Comment by the-maldridge** [comment]
Noted, I'll try and spin another set of ISOs and see if they are improved by the fixes.

**Comment by cr6git** [comment]
Oh no! Stupid me! :rage: 
I thought the bug was fixed, but I was wrong.
It's **not** fixed!
In fact, it only affects the **i686** version, hence my confusion...
I closed the issue too quickly, I'm truly sorry.

**Comment by cr6git** [comment]
@Piraty Did you try i686 ?

**Comment by the-maldridge** [comment]
Void no longer ships the linux4.18 kernels, thus I am marking this as closed.
