### ISSUE TITLE
Installer should set defaults for locale, even if user doesn't change anything

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-mklive#190]
The installer defaults to enabling the `en_US.UTF-8` locale (for glibc), but it leaves `LANG=` in `/etc/locale.conf`, instead of setting at least some value, if the user doesn't go into the locale dialog in the installer. This can lead to issues in some brittle environments: for example a Cinnamon local install won't be able to launch `gnome-terminal`.

This is easy to fix locally from a tty, but the installer shouldn't leave `LANG` empty by default. Let the people have UTF-8 :D

**Comment by classabbyamp** [comment]
done in b6edd4051bf7b777e67e9f3717e9e4194b707f2d
