### ISSUE TITLE
Request: live images burnable to CD-R (<700MB)

### ISSUE THREAD

**Issue by Tcll** [void-linux/void-mklive#195]
I have a use for older i686 machines, a few of which can't boot USB (older Pentium 4 or Pentium III boards)
I'd have to go out of my way to buy DVD-R disks, while I already have stacks of (at least 50 total) CD-R disks collecting dust...
(I'd prefer not to spend money if I don't need to)

I'm not sure what's involved to achieve what's needed
but I'd like to request live images burnable to CD-R (possibly separate from DVD-R images if that luxury can be provided)

**Comment by Johnnynator** [comment]
The non gui iso should fit on a CD-R just fine?
Furthermore LXDE iso is also only 698MiB (I wouldn't count on it staying under 700 in the future).

**Comment by Tcll** [comment]
I probably should've mentioned I prefer the XFCE image, my bad there...

but a live image is good for when you need to manage things before installing, such as running gparted or configuring the network before running the installation.

... ok sure, I have an Xubuntu 16.04 disk that has just about everything I need on it for that, but that's beside the point...
couldn't the Void XFCE live image be distributed to do everything the Xubuntu 16.04 live image does (maybe a bit less for some unneeded things), AND fit within 700MB??

you could reduce space by removing PulseAudio from the live image, as that's really not needed seeing as ALSA is already there...
(unless that's been done already)
you could add qas-tools or the xfce alsa mixer (same controls) just to give users a decent ALSA mixer to work with ;)

there's probably a few other things that could be removed from the live image as well to reduce space

why does Xubuntu 16.04 have to beat Void at being minimal??

---

so yeah, all I'm requesting is that Void is kept compatible for CD-R burning :)

... at least for most capable DEs that are designed to be minimal, like XFCE and LXDE...
I can understand something like Cinnamon, Gnome, or KDE not fitting on a CD-R ;)

**Comment by ahesford** [comment]
Void doesn't strive for minimalism, so it is not surprising that alternatives offer more compact images.

**Comment by ericonr** [comment]
The graphical live images are mostly a convenience Void offers, but not a main focus. Feel free to PR improvements that make them smaller (while maintaining sane defaults), or build them locally, perhaps without a browser?; but I will be closing the issue for now.

> why does Xubuntu 16.04 have to beat Void at being minimal??

You will note we ship software from this decade.

**Comment by Tcll** [comment]
... that's a shame... the main reasons I use void are minimalism and security (and because I was told it's the most BSD-like distro)

I guess all the stuff I've been praising Void for over the years has been rendered moot, making me the fool...
