### ISSUE TITLE
adding XZ in live enviroment...

### ISSUE THREAD

**Issue by hechos** [void-linux/void-mklive#196]
good afternoon guys i have been having see problems for a long time in mklive adding only "xz" as a program for example ./mklive.sh -p 'xz' the process ends successfully but xz does not appear in live environment, even when modify readonly REQUIRED_PKGS="base-files libgcc dash coreutils sed tar gawk syslinux grub-i386-efi grub-x86_64-efi squashfs-tools xorriso xz" still doesnt works.

**Comment by absolutelynothinghere** [comment]
I have this issue too, why was this closed?
