### ISSUE TITLE
Brightness too low for amdgpu_bl0 backlight

### ISSUE THREAD

**Issue by pyramidhead52** [void-linux/void-mklive#198]
Hardware: Huawei MateBook D 14 AMD Ryzen 5 3500u

When I booted the live ISO, the brightness is too low.

`cat /sys/class/backlight/*/brightness`
4

0-255 is the valid range and 4 is just barely visible. I could fix it with

`echo 102 > /sys/class/backlight/amdgpu_bl0/brightness` for about %40.

**Comment by paper42** [comment]
I installed Void using the latest ISO on Ryzen 7 3700U a few days ago without this issue.

**Comment by pyramidhead52** [comment]
It is the same on installed system. It's affecting the live installer too, but I guess the installer is not to blame.

Do you think it could be related to acpid?

**Comment by st3r4g** [comment]
I have the same laptop and yes, I experience this. But I don't think void can do much about it, it's probably something in the kernel. For example, if you try the 5.4 kernel, it boots to full brightness. Systemd distros have automatic load/save brightness on reboot. What I did was simply setting a saner level of brightness in `/etc/rc.local`

**Comment by pyramidhead52** [comment]
Thank you. rc.local workaround is all I need.

Since apparently this is a kernel/amdgpu bug, I close the issue.
