### ISSUE TITLE
dialog isn't installed on the live system 

### ISSUE THREAD

**Issue by 0x0f0f0f** [void-linux/void-mklive#20]
adding the package dialog using the -p option with mklive.sh doesn't actually install dialog on the live image, wtf?

x86_64-efi musl

**Comment by Vaelatern** [comment]
I'm not sure if we care to fix this.
Add dialog to your list of supplementary packages in the meanwhile.

**Comment by cr6git** [comment]
https://github.com/voidlinux/void-mklive/issues/117

**Comment by 0x0f0f0f** [comment]
I thought about writing a new installer in alpine linux's style.

Here are some useful tools  that could help us make a new cli installer:
* https://github.com/p-gen/smenu
* cfdisk
* add the choice to use `connman` to handle wifi connections by default (ikr, dbus 😢). wpa_supplicant and dhcpd hooks make it really annoying to handle wifi for void newcomers. connmanctl is much more straightforward than configuring wpa_supplicant
* written in golang or C for easier portability between platforms (musl & arm)
* add the choice to add (something similar to) [this](https://github.com/netzverweigerer/vpm), simplifying the xbps syntax to a single command, `apk` - like CLI interface
* ask to autoconfig xorg driver configurations

The current installer has some flaws. What about reducing the number of its dependencies? Setting passwords could be better instead of storing them in a plaintext file in /tmp

**Comment by 0x0f0f0f** [comment]
Woah! @the-maldridge do you have any details about the new installer?

**Comment by Vaelatern** [comment]
https://github.com/the-maldridge/vInstaller/

**Comment by the-maldridge** [comment]
It more or less works, but I'm still trying to decide how best to do some other tasks around filesystem setup and installer meta configuration.  I might have some interesting things working this weekend.

**Comment by the-maldridge** [comment]
As the original discussion of dialog has been resolved, I'm going to close this issue.
