### ISSUE TITLE
Feature request: Add the ability to select repository mirror from installer script

### ISSUE THREAD

**Issue by ajshell1** [void-linux/void-mklive#203]
Void is currently my favorite distro, but I've found that the default mirror (https://alpha.de.repo.voidlinux.org/) is a bit slow for me. Of course, that's a European mirror, so I imagine it's fast enough in Europe, but I'm an American. I've found that the other three Tier 1 American mirrors are MUCH better, but those aren't the default mirrors.

My concern is that some people (mostly Americans) might be put off by this slow download speed, especially since xbps is supposed to be a fast package manager. Here's a concrete example of this happening: https://www.reddit.com/r/voidlinux/comments/jwo8pu/just_installed_void_here_is_my_impression_if_any/

In addition, I installed Void on a laptop recently, and the first thing I did was change the mirrors. 

With this in mind, I think the option to select the mirror is something that would be a useful addition to the installer script.

Here's my basic layout idea:

After highlighting the "Select Mirror" menu option on the script, an informational box will provide some basic info, including the difference between Tier 1 and Tier 2 mirrors.

Then, another dialog menu will appear, with options corresponding to the region (i.e. EU, USA, AU, or Asia)

After selecting the mirror region, the user will be presented with a list of mirrors for that region, which includes the URL, the location in the region, and the tier status.

From there, the script would then run `sed -i 's|https://alpha.de.repo.voidlinux.org|<repository>|g' /etc/xbps.d/*-repository-*.conf` as described on the wiki.

I mainly care about this being run after the installation, so that the newly-installed system will have the right mirrors, although if the developers also want this to affect the mirrors used during the install, that would be neat as well.

**Comment by classabbyamp** [comment]
done in https://github.com/void-linux/void-mklive/pull/318
