### ISSUE TITLE
void-installer: Wireless configuration can't handle spaces in SSID or Password

### ISSUE THREAD

**Issue by ratfactor** [void-linux/void-mklive#204]
As also noted by @Pitasi in #5, the dialog for entering wireless configuration cannot handle spaces:

```
SSID:            _My_Sweet_Wifi__________________
Encryption:      _wpa_
Password:        _password_1234_______________________________________
```

In my case, I have spaces in my SSID and I kept getting a response of

```
Invalid encryption type (possible values: wep or wpa).
```

I finally realized that it was seeing "Sweet" from the example SSID as the encryption type.

Since the live image has Bash 5.1, this can be solved by changing:

```
    set -- $(cat $ANSWER)
    ssid="$1"; enc="$2"; pass="$3";
```

to

```
    readarray -t lines < $ANSWER
    ssid="${lines[0]}"; enc="${lines[1]}"; pass="${lines[2]}";
```

**I'd be happy to create a PR if this sounds like a good solution.**

I'm still having trouble with getting WiFi to work, but I'm hoping #156 will solve it.

**Comment by classabbyamp** [comment]
should be solved by #236
