### ISSUE TITLE
add service enablement to installer

### ISSUE THREAD

**Issue by oz42** [void-linux/void-mklive#209]
Please make daemons configurable in the installer.

**Comment by Vaelatern** [comment]
Could always chroot and link, but that's a very reasonable request.

**Comment by oz42** [comment]
I think of the FreeBSD way where I can tell what daemons should start

**Comment by Vaelatern** [comment]
Why did you close this

**Comment by oz42** [comment]
Sorry, I just wanted to comment.

**Comment by Animeshz** [comment]
I'd guess this is already done as a part of https://github.com/void-linux/void-mklive/commit/e132ea26f28ba6a360a7b20f0cf2482003801c67

**Comment by classabbyamp** [comment]
no, that's not the installer

**Comment by Animeshz** [comment]
-S option indeed works to enable the user specified services, isn't it the same?

**Comment by classabbyamp** [comment]
that enables them in the live image. this issue is about the installer
