### ISSUE TITLE
Feature request: rfkill in live image

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-mklive#22]
This is not super important, especially since I know what modules to blacklist for my one laptop, but a lot of laptops rfkill wireless and are not configured by default to turn it on via hardware switches. Since wireless utilities are included I think this could be a candidate for the next release of liveimages. 

I just thought I would formally suggest this. Thanks

**Comment by jnbr** [comment]
The current live images contain `usr/bin/rfkill`, provided by `util-linux`

**Comment by Vaelatern** [comment]
So this issue can be closed?

**Comment by bobertlo** [comment]
Sorry for not checking the new release, I just looked at the log. The production liveimages must be maintained off tree.
