### ISSUE TITLE
mt7921 wireless driver failed with status -2

### ISSUE THREAD

**Issue by 4d30** [void-linux/void-mklive#224]
I just downloaded and wrote the image at https://alpha.de.repo.voidlinux.org/live/current/void-live-x86_64-20210930.iso to install on a laptop with a MediaTek mt7921 wireless adapter. The module in this image for this device fails to load with status -2.

Afterwards, I tried images from other distributions and the module/device comes up and wireless connectivity is unimpeded. Updating the image to include newer kernel/firmware would probably solve this.

**Comment by JamiKettunen** [comment]
New images are being prepared (#284), this issue is a bit pointless if there's no confirmation what exactly might fix the problem. There's also an absence of any kind of logs so it's all up to interpretation what the problem could be if it "works on other distros".

Can you try building a new image locally and checking if that helps, or trying the upcoming `20221001` images when they release?

**Comment by 4d30** [comment]
Without a wireless driver, it was difficult for me to get the logs off the device. Most folks just say "thank you."  

FWIW, this is how loading works on another distro:

```
$ uname -a                
Artix Linux localhost 5.15.64-1-lts #1 SMP Wed, 31 Aug 2022 21:14:32 +0000 x86_64 GNU/Linux
$ sudo dmesg | grep mt7921
[    2.599372] mt7921e 0000:03:00.0: enabling device (0000 -> 0002)
[    2.599634] mt7921e 0000:03:00.0: disabling ASPM  L1
[    2.599638] mt7921e 0000:03:00.0: can't disable ASPM; OS doesn't have ASPM control
[    2.613436] mt7921e 0000:03:00.0: ASIC revision: 79610010
[    2.723254] mt7921e 0000:03:00.0: HW/SW Version: 0x8a108a10, Build Time: 20220608210839a
[    3.004359] mt7921e 0000:03:00.0: WM Firmware Version: ____010000, Build Time: 20220608210922
[    3.032637] mt7921e 0000:03:00.0: Firmware init done
```

Then my recollection for how may have looked on Void last year would have been something like

[    2.599372] mt7921e 0000:03:00.0: enabling device (0000 -> 0002)
[    2.599634] mt7921e 0000:03:00.0: disabling ASPM  L1
[    2.599638] mt7921e 0000:03:00.0: can't disable ASPM; OS doesn't have ASPM control
[    2.723254] mt7921e 0000:03:00.0: module failed to load with status -2

**Comment by JamiKettunen** [comment]
Sorry, I meant the problem is it's a bit difficult for us to try and fix it unless we have the hardware, thus if you build a new image locally it should have an up-to-date kernel and firmware which as you speculated could fix the issue.

A picture of `dmesg` with the exact error could do as well, as that `module failed to load with status -2` is way too generic to track down and in fact `grep -r . -e 'failed to load with'` in root of kernel source didn't give me any results.

**Comment by JamiKettunen** [comment]
Seems the `20221001` images are now public, so you can just download it from https://voidlinux.org/download/ like normal. Let me know how it goes!

**Comment by 4d30** [comment]
I'll write an image when I get off work to test 'er out

**Comment by 4d30** [comment]
I wrote the image at https://repo-default.voidlinux.org/live/current/void-live-x86_64-20221001-base.iso to a disk. Then this disk was used to boot my device with a MediaTek Mt7961 wireless adapter. It failed to load the module with error -2.

I took some photos with a potato of the error message:

![IMG_0151](https://user-images.githubusercontent.com/45021583/196313372-778ffc78-53a0-48ad-84a6-2e749a505058.jpg)
![IMG_0150](https://user-images.githubusercontent.com/45021583/196313373-fdf7ac95-2d1d-489c-9664-21ce721878b7.jpg)


This message is printed (10) times:

`mt7921e 0000:03:00.0: Direct firmware load for mediatek/WIFI_MT7961_patch_mcu_1_2_hdr.bin failed with error -2`

Then this message once:

`mt7921e 0000:03:00.0: hardware init failed`

**Comment by JamiKettunen** [comment]
I can at least tell the [`linux-firmware` package](https://github.com/void-linux/void-packages/blob/master/srcpkgs/linux-firmware/template) is out-of-date by some 4 months during which [`WIFI_MT7961_patch_mcu_1_2_hdr.bin`](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/mediatek/WIFI_MT7961_patch_mcu_1_2_hdr.bin) has also received a few updates upstream :/

The hash of this problematic file on the MEGA archive matches that of [the second latest update to the file](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/mediatek/WIFI_MT7961_patch_mcu_1_2_hdr.bin?id=34c8eea52f63b9e9acaae50fb3a661f64c0518e0) fwiw.

I do wonder if [the latest version of the file](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/mediatek/WIFI_MT7961_patch_mcu_1_2_hdr.bin) would work if you just copy it to `/usr/lib/firmware/mediatek/WIFI_MT7961_patch_mcu_1_2_hdr.bin`, then attempt to re-probe the driver with `rmmod mt7921e && modprobe mt7921e`, it'll probably be more convenient to try this with the XFCE image flavor so you can copy things around easier from another USB device (or another OS install where it works) for example.

Let me know if you have any more progress!

**Comment by JamiKettunen** [comment]
Found the problem, there is no `/usr/lib/firmware/mediatek` included on the live images currently, https://github.com/void-linux/void-packages/pull/36120 would address this as `linux-firmware-network` is indeed installed, just not the full `linux-firmware` which currently contains all of `/usr/lib/firmware/mediatek`.
