### ISSUE TITLE
[Bug?] void-installer on xfce iso glitches when moving around the terminal

### ISSUE THREAD

**Issue by Username58260** [void-linux/void-mklive#228]
When you start the installation of void and move around the terminal it glitches out:

![FileName__0](https://user-images.githubusercontent.com/95015583/147399554-531fbe0f-e8a2-4a8c-9307-61f9e04e1df2.jpg)

Once the installation gets to "Rebuilding initramfs for target" it fixes itself.

**Comment by abenson** [comment]
By "moving" do you mean "resizing"?

**Comment by Duncaen** [comment]
Dialog is still running, not sure if when using auto sizing instead of fixed values it might listen for SIGWINCH and redraw.
