### ISSUE TITLE
mkimage fails to make image from rootfs

### ISSUE THREAD

**Issue by Yush08** [void-linux/void-mklive#230]
I made a rootfs -- `./mkrootfs.sh x86_64-musl`, but then when I ran mkimage i got this error - `FATAL: The ./void-x86_64-musl-ROOTFS-20220118.tar.xz is not supported, exiting...`

this happens on the glibc rootfs as well

**Comment by the-maldridge** [comment]
Working as intended.  mkimage is for arm platforms and requires a PLATFORMFS, not a ROOTFS bundle.
