### ISSUE TITLE
RockPro64 Support?

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-mklive#238]
Does the rock64 platform work for RockPro64 as well?

https://github.com/void-linux/void-mklive/commit/388993eb513a7af0bc33bbc57bc0a6ff941778f4

**Comment by paper42** [comment]
#221

**Comment by Anachron** [comment]
Thanks. Github search is either terrible or I have no idea what I searched for.

Can someone tell me how good the support is?

**Comment by Anachron** [comment]
Closing, will buy a RockPro64 myself and give feedback.
