### ISSUE TITLE
Old urls in installation script and live /etc/issue

### ISSUE THREAD

**Issue by voidpin** [void-linux/void-mklive#24]
@the-maldridge, I was refering to the installer on the November 2018 .iso images.
So what exactly do you mean with "not installed anywhere"?
To be honest, and as mentioned, it doesn't bother me. Just thought, you would like to know about it.
Have a good day and close this issue as fast as you can.

**Comment by voidpin** [comment]
Closing.

**Comment by Duncaen** [comment]
The void installer lives in this repository, the other repository is not code that is used anywhere.

The `void-installer` in this repository still has references to the old repository, this issue is correct.

https://github.com/void-linux/void-mklive/search?q=voidlinux.eu&unscoped_q=voidlinux.eu

**Comment by voidpin** [comment]
@Duncaen
I've realized later that this was the case. I'm sorry for posting in the wrong place to start with.
Thx!
As I wrote in my original post, thx for the great work you guys do.

**Comment by the-maldridge** [comment]
Resolved by #41
