### ISSUE TITLE
Dracut error after building x86_64 iso's 

### ISSUE THREAD

**Issue by WilliamBehrens** [void-linux/void-mklive#248]
![image](https://user-images.githubusercontent.com/35979547/165406728-d10d6363-edf0-4927-abca-0e4b33431f13.png)

I ran the script to build the iso's for x86 and attempted to boot one and got the above error from dracut, I get this error when trying to build custom images as well.

**Comment by Vaelatern** [comment]
`root=?`

**Comment by WilliamBehrens** [comment]
> `root=?`

what does this mean?

**Comment by Vaelatern** [comment]
what is your kernel commandline argument for `root=`?

**Comment by WilliamBehrens** [comment]
there isn't one being set

**Comment by Vaelatern** [comment]
Well, set one.

**Comment by WilliamBehrens** [comment]
to what?

**Comment by WilliamBehrens** [comment]
> Well, set one.

so what is it's value supposed to be?

**Comment by Vaelatern** [comment]
You can choose. On a recent machine I set root=/dev/null
Just something that will be a root.

**Comment by WilliamBehrens** [comment]
> You can choose. On a recent machine I set root=/dev/null Just something that will be a root.

That doesn't even make sense?

I set it to /dev/null and tried it and I get `/dev/null is not a valid block device`

Can you actually explain to me the error rather then being unhelpful

**Comment by Vaelatern** [comment]
Here's the simple version:

Can't mount root filesystem

Wasn't told where to find a root filesystem.

Can't mount if you don't know what to mount.

`root=` tells everybody where to find the root filesystem. Sometimes it's `root=ZFS=$THING` and other times `root=/dev/null`.

**Comment by WilliamBehrens** [comment]
so how can I find what it is for the iso?

**Comment by Vaelatern** [comment]
I recommend looking at how `make` builds these images, I have not had this problem when building an image through the `Makefile`

**Comment by WilliamBehrens** [comment]
> I recommend looking at how `make` builds these images, I have not had this problem when building an image through the `Makefile`

A quick search of the Makefile shows that `root=` doesn't exist

**Comment by Vaelatern** [comment]
Somehow in the way it builds, it doesn't need it.
