### ISSUE TITLE
rpi4 live image too old for current board

### ISSUE THREAD

**Issue by manfredu** [void-linux/void-mklive#264]
To check the gnucash build on arm (See [List of broken native aarch64-musl builds #37497](https://github.com/void-linux/void-packages/issues/37497)) I tried to boot void on a rpi4 4 GB by using the rpi4 live image musl from https://voidlinux.org/download/, but this img file seems to be too old:

```
start4.elf: is not compatible
This board requires newer software
Get the latest software from https://www.raspberrypi.org/downloads/
```

**Comment by sanderboer** [comment]
I can second this issue, but with aarch64 glibc version on an rpi 4  8gb board.

**Comment by manfredu** [comment]
I believe the live image on the download page still needs to be recreated so that it does work.

But it should now be possible to create a working image by using the scripts from [void-mklive](https://github.com/void-linux/void-mklive). See also https://github.com/void-linux/void-mklive/issues/126.
