### ISSUE TITLE
How to add custom xbps packages into the iso?

### ISSUE THREAD

**Issue by johna23-lab** [void-linux/void-mklive#266]
I have several xbps packages for personal use and i wonder if it is possible to add them when making a custom iso.

I have previously been following this manuals 

https://docs.voidlinux.org/xbps/repositories/signing.html
https://voidlinux.org/news/2014/01/create-repos.html

Everything has been fine but at the time of making the iso with the following parameters

sudo ./mklive.sh -a x86_64 -r http://192.168.122.1/void/current -p package-1.1_1.xbps 

After a few seconds it gives me the following message

Package 'package-1.1_1.xbps' not found in repository pool.
ERROR: Missing required binary packages, exiting...

The http://192.168.122. works and the ./mklive.sh connects to the site but does not recognize the new package even though it is indexed.

Any ideas/suggestions?

Thanks

**Comment by Duncaen** [comment]
remove `.xbps`.

**Comment by johna23-lab** [comment]
This steps are worked

openssl genrsa -des3 -out privkey.pem 4096
xbps-rindex -a -f  www/void_repo/current/x86_64-repodata/*.xbps
xbps-rindex --sign --signedby 'foo <foo@foo.org>' --privkey privkey.pem www/void_repo/current/x86_64-repodata

Then i do
sudo ./mklive.sh -a x86_64 -r http://192.168.229.214/void_repo/current -p package-1.1_1

and i get 

[*] Updating repository `http://192.168.229.214/void_repo/current/x86_64-repodata' ...
x86_64-repodata: 603KB

and then 

[3/9] Installing void pkgs into the rootfs: base-system  package-1.1_1 ...
Package 'xed-edit-3.2.4_1' not found in repository pool.
ERROR: Missing required binary packages, exiting..

And the file is there with the other files

**Comment by classabbyamp** [comment]
did you add the package to the repo index? (xbps-rindex -a)

**Comment by johna23-lab** [comment]
> did you add the package to the repo index? (xbps-rindex -a)
I think so

sudo xbps-install -S
[*] Updating repository `https://mirrors.dotsrc.org/voidlinux/current/x86_64-repodata' ...
[*] Updating repository `https://mirrors.dotsrc.org/voidlinux/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://mirrors.dotsrc.org/voidlinux/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://mirrors.dotsrc.org/voidlinux/current/nonfree/x86_64-repodata' ...

/home/void/Downloads/binpkgs/' repository has been RSA signed by "foo foo@foo.org"
Fingerprint: e23e2ee
Do you want to import this public key? [Y/n] Y

xbps-query -L
12973 https://mirrors.dotsrc.org/voidlinux/current (RSA signed)
   26 https://mirrors.dotsrc.org/voidlinux/current/multilib/nonfree (RSA signed)
 5446 https://mirrors.dotsrc.org/voidlinux/current/multilib (RSA signed)
    **2 /home/void/Downloads/binpkgs/ (RSA signed)**

xbps-rindex -a -f /home/void/Downloads/binpkgs/*.xbps
index: added `cde-2.4.0_7' (x86_64).
index: **2 packages registered.**

sudo ./mklive.sh -a x86_64 -r /home/void/Downloads/binpkgs -p package.4.0_1

[3/9] Installing void pkgs into the rootfs: base-system package.4.0_1 ...
Package 'cde-2.4.0' not found in repository pool.
ERROR: Missing required binary packages, exiting..

**Comment by johna23-lab** [comment]
Thanks for the ideas/help looks i solved the problem, this is what i did, maybe this steps can help some people

#https://voidlinux.org/news/2014/01/create-repos.html

To add a custom repository, create a file called "my-remote-repo.conf" in /etc/xbps.d

repository=/home/void/voidpackages/voidlinux/current/

Copy all the *.xbps and *.sig in that folder

Then create the SRA private key

openssl genrsa -des3 -out privkey.pem 4096
generating RSA private key, 4096 bit long modulus (2 primes)
Enter pass phrase for privkey.pem

xbps-rindex -a /home/void/voidpackages/voidlinux/current/*.xbps

index: added `FeatherPad-1.3.0_1' (x86_64).
index: added `brave-bin-1.41.96_1' (x86_64).
index: 1126 packages registered

xbps-rindex --sign --signedby 'foo <foo@foo.org>' --privkey privkey.pem  /home/void/voidpackages/voidlinux/current
Enter PEM pass phrase:
Initialized signed repository (1126 packages)

sudo ./mklive.sh -a x86_64 -r /home/void/voidpackages/voidlinux/current -p brave-bin-1.41.96_1

/home/void/voidpackages/voidlinux/current' repository has been RSA signed by "foo <foo@foo.org>"
Do you want to import this public key? [Y/n] Y


/home/void/voidpackages/voidlinux/current' repository has been RSA signed by "foo <foo@foo.org>"
Do you want to import this public key? [Y/n] Y

Looks good...
[3/9] Installing void pkgs into the rootfs: base-system brave-bin-1.41.96 ... 

brave into the system \o/
brave-bin-1.41.96_1: unpacking 

And there is!
xbps-query -m
base-system-0.114_1
brave-bin-1.41.96_1
