### ISSUE TITLE
create UEFI only void-iso?

### ISSUE THREAD

**Issue by wael444** [void-linux/void-mklive#270]

**Comment by classabbyamp** [comment]
can you elaborate?

**Comment by wael444** [comment]
would it possible to build the iso with custom `xorriso` parameters such so that the iso itself can only be booted on an UEFI system?

currently looking to build my own void iso but i would like to limit it to only UEFI systems.

**Comment by Vaelatern** [comment]
why would you want this?

**Comment by wael444** [comment]
currently getting close, getting this error: 

![image](https://user-images.githubusercontent.com/47404953/179053144-884231a7-0ebf-4e72-8105-179c8a240c2f.png)

**Comment by paper42** [comment]
> as i am doing other things that conflict with BIOS.

could you elaborate on that?

**Comment by wael444** [comment]
I am using `gummiboot` as the UEFI bootloader.

**Comment by the-maldridge** [comment]
Out of scope for mklive.
