### ISSUE TITLE
20221001 Coordination Ticket

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-mklive#284]
All information related to the testing of the 20221001 image set should be in this thread.

**Comment by classabbyamp** [comment]
tested these live images:
- `rpi-armv6l-musl` on rpi 1a+
- `rpi-armv7l` on rpi 2b
- `rpi-aarch64-musl` on rpi 3b and 02W (same SD card, even)

all work well

**Comment by classabbyamp** [comment]
related PRs:

- https://github.com/void-linux/void-docs/pull/710
- https://github.com/void-linux/void-linux.github.io/pull/183
- https://github.com/void-linux/void-linux.github.io/pull/182

**Comment by classabbyamp** [comment]
tested the installer on `x86_64-musl`, works well (but there were unrelated mac-caused bootloader troubles)

**Comment by Vaelatern** [comment]
Validated that my issue with the autoinstaller where I couldn't list multiple packages is fixed (tested x86_64. Was able to fully build my machines without overriding `VAI_install_base_system()`

**Comment by the-maldridge** [comment]
We appear to be satisfied with the new images.  If there are no other concerns I will copy them to the main mirror, sign, and release.

**Comment by the-maldridge** [comment]
New images have been pushed, we can return to being dead for another year.
