### ISSUE TITLE
mklive command error: dracut module 'autoinstaller' cannot be found or installed

### ISSUE THREAD

**Issue by ipiazza** [void-linux/void-mklive#285]
Hello team,
I am trying to build a custom image by running the following command.

`[root@ivan-laptop void-mklive]# ./mklive.sh -a x86_64-musl -k it -b base-minimal -p "neovim htop dhcpcd docker docker-cli docker-compose openssh openssl sqlite" -v "linux5.19" -I ./include-dir -S "sshd dhcpcd" -C " net.ifnames=0"
`

But I am getting the following error message:

-----------------
...
[6/10] Generating initramfs image (xz)...
findmnt: can't read /proc/mounts: No such file or directory
dracut: Executing: /usr/bin/dracut -N --xz --add-drivers ahci --force-add "vmklive autoinstaller" --omit systemd /boot/initrd 5.19.13_1
dracut: dracut module 'mksh' will not be installed, because command '/bin/mksh' could not be found!
[...]
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack
[...]
dracut: dracut module 'autoinstaller' cannot be found or installed.
ERROR: Failed to generate the initramfs

------------------

Full output is available at this pastebin [link](https://pastebin.com/jzNae2CN)

Can anybody point me towards what I am doing wrong? Thanks!

**Comment by classabbyamp** [comment]
I can only repro this with `-b base-minimal`, so it seems dracut has under-specified dependencies

**Comment by ipiazza** [comment]
I've just finished trying adding one of the 68 packages in base-system and it always failed. Maybe it's a combination of more than a package. Defaulting to base-system instead of base-minimal for now. It would be good to make it working also with base-minimal.

**Comment by the-maldridge** [comment]
You can check which binaries it installs and which package provides those,
that should tell you what is missing.

**Comment by ipiazza** [comment]
I wasn't clear with my previous statement. I tried to add with the `-p` flag each of the 68 packages that are in base-system but always a single package. I guess dracut needs some and thus the single addition didn't work.
I will make some tries and see if I can find the minimum package-set needed to make dracut work.

**Comment by ipiazza** [comment]
so, after some attempts I was able to properly build a custom void live image using the **base-minimal** system package by adding to the `-p` list the two packages `iproute2 iputils`.

What's the right way to request to add those two packages to the **base-minimal** system package in order to have a smooth image creation?

Down below the partial (only the dracut lines) output of the mklive.sh I run. Full output available [here](https://pastebin.com/27DX7V4S)

-------------------

[6/10] Generating initramfs image (xz)...
dracut: Executing: /usr/bin/dracut -N --xz --add-drivers ahci --force-add "vmklive autoinstaller" --omit systemd /boot/initrd 5.19.13_1
dracut: dracut module 'mksh' will not be installed, because command '/bin/mksh' could not be found!
dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'dbus-broker' will not be installed, because command 'busctl' could not be found!
dracut: dracut module 'dbus-daemon' will not be installed, because command 'busctl' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'i18n' will not be installed, because command 'setfont' could not be found!
dracut: dracut module 'i18n' will not be installed, because command 'loadkeys' could not be found!
dracut: dracut module 'i18n' will not be installed, because command 'kbd_mode' could not be found!
dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!
dracut: dracut module 'url-lib' will not be installed, because command 'curl' could not be found!
dracut: dracut module 'lvmmerge' will not be installed, because command 'lvm' could not be found!
dracut: dracut module 'btrfs' will not be installed, because command 'btrfs' could not be found!
dracut: 90crypt: Could not find any command of '/systemd-cryptsetup cryptsetup'!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'dmsquash-live-ntfs' will not be installed, because command 'ntfs-3g' could not be found!
dracut: dracut module 'lvm' will not be installed, because command 'lvm' could not be found!
dracut: dracut module 'mdraid' will not be installed, because command 'mdadm' could not be found!
dracut: dracut module 'multipath' will not be installed, because command 'multipath' could not be found!
dracut: dracut module 'crypt-gpg' will not be installed, because command 'gpg' could not be found!
dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fcoemon' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fcoeadm' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: dracut module 'nbd' will not be installed, because command 'nbd-client' could not be found!
dracut: 95nfs: Could not find any command of 'rpcbind portmap'!
dracut: dracut module 'nvmf' will not be installed, because command 'nvme' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack
dracut: dracut module 'squash' will not be installed, because command 'mksquashfs' could not be found!
dracut: dracut module 'squash' will not be installed, because command 'unsquashfs' could not be found!
dracut: *** Including module: bash ***
dracut: *** Including module: dash ***
dracut: *** Including module: autoinstaller ***
dracut-install: ERROR: installing '/usr/bin/clear'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.hdssua/initramfs /usr/bin/clear
dracut-install: ERROR: installing '/usr/bin/mkfs.ext4'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.hdssua/initramfs /usr/bin/mkfs.ext4
dracut: *** Including module: vmklive ***
dracut: *** Including module: network-legacy ***
dracut: *** Including module: network ***
dracut: *** Including module: drm ***
dracut: *** Including module: dm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 60-persistent-storage-dm.rules
dracut: Skipping udev rule: 55-dm.rules
dracut: *** Including module: dmsquash-live ***
dracut: *** Including module: kernel-modules ***
dracut: *** Including module: kernel-modules-extra ***
dracut: *** Including module: kernel-network-modules ***
dracut: *** Including module: nvdimm ***
dracut: *** Including module: qemu ***
dracut: *** Including module: qemu-net ***
dracut: *** Including module: lunmask ***
dracut: *** Including module: resume ***
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: terminfo ***
cp: cannot stat '/usr/share/terminfo/l/linux': No such file or directory
cp: cannot stat '/usr/share/terminfo/v/vt100': No such file or directory
cp: cannot stat '/usr/share/terminfo/v/vt102': No such file or directory
cp: cannot stat '/usr/share/terminfo/v/vt220': No such file or directory
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: usrmount ***
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including module: img-lib ***
dracut: *** Including module: shutdown ***
dracut: *** Including modules done ***
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done ***
dracut: *** Hardlinking files ***
Mode:                     real
Method:                   sha256
Files:                    1457
Linked:                   0 files
Compared:                 0 xattrs
Compared:                 91 files
Saved:                    0 B
Duration:                 0.034313 seconds
dracut: *** Hardlinking files done ***
dracut: *** Generating early-microcode cpio image ***
dracut: *** Store current command line parameters ***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Creating image file '/boot/initrd' ***
dracut: *** Creating initramfs image file '/boot/initrd' done ***

------------------

**Comment by ipiazza** [comment]
closing this issue as base-minimal is not meant for live images but instead of docker containers and the like. base-voidstrap has to be used for to get an image slimmer than base-system
