### ISSUE TITLE
Size discrepancy with official and custom live image

### ISSUE THREAD

**Issue by Zapeth** [void-linux/void-mklive#286]
If I build a custom image with `sudo ./mklive.sh -v linux5.13` (same linux version as current live image) I get a 788MB image.

The official live image (base) is 542MB which makes a difference of 246MB, so I'm wondering where this difference comes from. Are there different parameters for constructing the official images, if yes what are they?

I also noticed the linux5.19 kernel was still downloaded when building the image despite me specifying an older version, ~but according to [this issue](https://github.com/void-linux/void-mklive/issues/128) it shouldn't be installed, so I guess thats not it? (I didn't actually check)~ Nevermind, I misread the comments. The downloaded package for linux5.19 is about 160MB which I guess could extract to the above mentioned size difference?

**Comment by classabbyamp** [comment]
does this also happen when using the `build-x86-images.sh` script?

**Comment by Zapeth** [comment]
With `build-x86-images.sh` I get a 663MB image, so still more than 100MB difference.

It looks like the script always uses the latest linux version, but I also don't think that the kernel space requirements would change that much from 5.13 to 5.19

**Comment by Duncaen** [comment]
firmware changes that much

**Comment by Zapeth** [comment]
Yeah, I noticed these packages were also pretty significant in size when they were downloaded during the build, but +100MB over just ~1 year is still questionable in my opinion.

Is there a way to verify this? If there is an xbps command to list the sizes of all installed packages on the system that would be ideal, but assuming its just the kernel and firmware packages, which directories would I have to check the sizes of for a comparison?

**Comment by classabbyamp** [comment]
`xhog` from `xtools`

**Comment by Duncaen** [comment]
Well you can compare the "source tarball" for the linux-firmware repo, 

```
linux-firmware-20220411.tar.gz                     25-Apr-2022 08:59           406388354
linux-firmware-20210511.tar.gz                     31-Aug-2021 02:31           324273766
```

This is the newest and the oldest version we mirror at https://sources.voidlinux.org.

**Comment by Zapeth** [comment]
Thanks for the suggestions, I compared the outputs of `xhog` in the official image with the one in the custom images. Here are the outputs of the last few lines for each (the most affecting packages):
- void-live-x86_64-20210930.iso (
```
linux-firmware-intel-20210818_1      16MB
coreutils-8.32_4                     17MB
linux-firmware-broadcom-20210818_1   18MB
glibc-locales-2.32_2                 19MB
grub-2.06_2                          29MB
glibc-2.32_2                         33MB
linux-firmware-amd-20210818_1        56MB
linux5.13-5.13.19_1                  120MB
linux-firmware-network-20210818_1    297MB
```
- void-live-x86_64-20221008-build.iso (663MB)
```
coreutils-8.32_4                     17MB
linux-firmware-broadcom-20220411_1   18MB
linux-firmware-intel-20220411_1      18MB
glibc-locales-2.32_2                 19MB
grub-2.06_2                          29MB
glibc-2.32_2                         33MB
linux-firmware-amd-20220411_1        66MB
linux5.19-5.19.13_1                  170MB
linux-firmware-network-20220411_1    381MB
```

Obviously `linux-firmware-network` is the biggest factor here with a 84MB size increase, then the kernel with 50MB. As for the image built with `mklive.sh`, here the extra installed 5.13 kernel takes up additional 120MB.

Considering the `linux-firmware-network` package takes up more than half of the entire image I think it would be nice to be able to exclude this (and other firmware packages) from the custom image, but thats another topic.

As for this issue, the above listings are a good enough explanation for me so I'll close it again.
