### ISSUE TITLE
Livecd problem

### ISSUE THREAD

**Issue by superiums** [void-linux/void-mklive#291]
# problem 1
after install void via local repo of the livecd published this mouth, the greeter not show.
in log file it reports:
```
Authorization required, but no authorization protocol specified
```

i selected root role and kept others as default during role choose.

this also happens on my previous installation on another computer : installed from the local repo of livecd published **Last Year**, after install, booted to the desktop. but after ` xbps-install -Su`
the greeter fails as reported above.

i don't know the reason, solved by install greetd and tuigreeter.

hope to fix this for fresh users.

# problem 2
after fresh install, there's no sound.
i sovled this by install alsa-utils and ` amixier sset Master unmute`.
by the way , it also lacks `pavucontrol` for fresh install.

hope to fix this for  fresh users.

**Comment by classabbyamp** [comment]
problem 1:
1. you shouldn't be adding yourself to the root group, use sudo/doas/su instead
2. I cannot reproduce this on x86_64 glibc, 20221001 xfce image, local install, with or without my user in the root group

however, the next live image will use lightdm so i doubt this problem will happen again

problem 2:
this is probably just caused by your hardware. it happens for some people.

**Comment by superiums** [comment]
maybe we could make the installation portable by add a config backup/ load config from backup.

when i complelted my config during installation, i could backup my config to a file.
next install (maybe from different pc) could load it from the config.

this feature is useful to transfer it to other people, make fresh user install void more easily. it's also helpful to enhance comunication between void users and developers and helpful to debug such problems.

**Comment by classabbyamp** [comment]
you can already save/load a config for the installer
