### ISSUE TITLE
Latest i686 image appears to be broken

### ISSUE THREAD

**Issue by cottnn** [void-linux/void-mklive#292]
I tried running the latest i686 live image ([void-live-i686-20221001-base.iso](https://repo-default.voidlinux.org/live/current/void-live-i686-20221001-base.iso)) in QEMU via virt-manager and it looks like it's currently broken. The root filesystem cannot be mounted for some reason, and so the user is dropped into a debug shell. I can't reproduce the same issue with the previous version of the image ([void-live-i686-20210930.iso](https://repo-default.voidlinux.org/live/20210930/void-live-i686-20210930.iso))

It's unlikely to be a QEMU issue since the previous version of the live CD works fine

![image](https://user-images.githubusercontent.com/91921136/198583135-194d56e3-d65f-44bc-8f23-93e287bb8b9b.png)
![image](https://user-images.githubusercontent.com/91921136/198583921-5acde0da-1ba8-442a-8510-2933231fd0db.png)

**Comment by leahneukirchen** [comment]
For some reason the ext3 is corrupted. fscking it after copying it to a readable location seems to fix it, so the data is there in principle.

**Comment by strec007** [comment]
I tested it on real Hardware and I can confirm that the issue exists there as well.

**Comment by classabbyamp** [comment]
trying to reproduce this now, can any of y'all test these images:

- https://devspace.voidlinux.org/abby/mklive-292/void-live-i686-20230418-base.iso
- https://devspace.voidlinux.org/abby/live-ci-test/void-live-i686-20230409-base.iso

both work for me in qemu/virt-manager

**Comment by strec007** [comment]
The first one works.
![img](https://user-images.githubusercontent.com/10652076/233061627-37f29fdd-bd8a-4a10-85a0-09cf36e0e1ac.jpg)

**Comment by vprime** [comment]
Both work here too
![image](https://github.com/void-linux/void-mklive/assets/1724913/f2920cb7-5d63-4094-b4cc-5ce653669d0a)

**Comment by classabbyamp** [comment]
please test these images for i686 compatibility: https://devspace.voidlinux.org/abby/live/void-live-20230628/

**Comment by classabbyamp** [comment]
should be solved by the 20230628 images
