### ISSUE TITLE
How i can add a custom bashrc in the livecd?

### ISSUE THREAD

**Issue by johna23-lab** [void-linux/void-mklive#303]
Hi! i want to add a custom bashrc and a custom gktrc in the LIVECD, it is possible?

Here is the bashrc
https://pastebin.com/pnfhytkA

Here is the gktrc
https://pastebin.com/4JrnsmFk

Thanks!

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-mklive/blob/master/mklive.sh.in#L80

do something like
```
somedir/home/anon/.bashrc
somedir/home/anon/.gtkrc
```
and
```
./mklive.sh -I somedir ...
```

**Comment by johna23-lab** [comment]
Thanks , the LIVECD worked well, but once installed the configuration is lost, how can i make it apply to the user of the installation?

**Comment by classabbyamp** [comment]
you would need to choose the local install method, but I'm not sure if it copies /home. either way you'd be better off using a dotfile manager for this, maybe something like stow or chezmoi

**Comment by johna23-lab** [comment]
I found a solution from this post
https://askubuntu.com/questions/971836/at-what-point-is-the-bashrc-file-created

Before creating the iso, the .bashrc file in the /etc/skel directory must be overwritten

**Comment by paper42** [comment]
This is not relevant to void-mklive anymore
