### ISSUE TITLE
How can add GRUB_DISABLE_OS_PROBER=false in the installer?

### ISSUE THREAD

**Issue by johna23-lab** [void-linux/void-mklive#304]
How/where i can add the line in the installer of the void-mklive?

GRUB_DISABLE_OS_PROBER=false

Thanks!

**Comment by classabbyamp** [comment]
you might be able to have a custom /etc/default/grub using the include dir feature of mklive but i think this is out of scope for the installer. this would be the domain of ansible or a similar tool
