### ISSUE TITLE
useradd/chpasswd in installer fails with errors

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-mklive#306]
can reproduce this: https://old.reddit.com/r/voidlinux/comments/zy6k6p/bug_installing_with_network_source_makes_no/

errors:

![image](https://user-images.githubusercontent.com/5366828/209992239-0b140fc9-3ca5-49ef-9cac-751934c1b94a.png)

**Comment by paper42** [comment]
maybe related to this 4 year old issue: #18

**Comment by rudzik8** [comment]
Thanks for creating the GH issue.

**Some details:** for me this only occurs when the installation source is set to 'Network', but other users reported that it happens for them too but not in exactly the same case. Check the Reddit post linked, it contains more information.

---

> maybe related to this 4 year old issue: #18

Maybe. It also says that the 'Network' installation source makes the bug appear (which was the case for me), but the final error that `chpasswd` outputs is different.
`line 1: user 'x' does not exist` vs `Cannot determine your user name`

**Comment by classabbyamp** [comment]
after some extensive testing, I have found that this only happens with glibc 2.32 but not with glibc 2.36, and does not happen on musl images.

This issue will be solved the next time images are generated.
