### ISSUE TITLE
ntp by default

### ISSUE THREAD

**Issue by rssmith544** [void-linux/void-mklive#308]
I think ntp should be installed by default on i686 image. I had an old laptop that the hardware clock was off and couldn't pull any packages or updates from the repos. I had to install another distro with ntp to set the clock and then reinstalled void and everything worked fine. i don't know much though and there may have been an easier way but it is just a suggestion.

**Comment by classabbyamp** [comment]
you don't need ntp to set the clock, you can use `date --set`

**Comment by paper42** [comment]
* how to change time is documented in the handbook which is also available on the live iso.
* this would mean another difference between the installed system and the iso which is not really what we want
* ntp can easily be installed on the live iso if the user needs it
* the hardware clock should hold the time, if it doesn't, it's trivial to set it and the user should change the battery

I am against this proposal
