### ISSUE TITLE
[RFC] include xmirror in the installer flow

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-mklive#317]
not sure where xmirror would fit in the installation flow... looking for advice

**Comment by the-maldridge** [comment]
It basically has to fit after network configuration and after source selection, as it makes no sense to do xmirror if the source is local.  I also think network should move after source selection since there's not much point in bringing up the network if the source is local.

**Comment by classabbyamp** [comment]
i believe if you bring up the network when doing a local install it will copy those configs over and enable the service?
