### ISSUE TITLE
SysLinux files are now installed to /usr/lib/syslinux: breaking changes to mklive

### ISSUE THREAD

**Issue by silvernode** [void-linux/void-mklive#32]
The mklive scripts are set to look for syslinux related files in `/usr/share/syslinux` but recently it appears that the syslinux package has changed to placing it's files in `/usr/lib/syslinux`. 

This change causes the problem below: 
```
[5/9] Generating isolinux support for PC-BIOS systems...
cp: cannot stat '/home/mollusk/git/butter/void-mklive/tmp.E78xFIo6BT/void-host/usr/share/syslinux/isolinux.bin': No such file or directory
cp: cannot stat '/home/mollusk/git/butter/void-mklive/tmp.E78xFIo6BT/void-host/usr/share/syslinux/ldlinux.c32': No such file or directory
cp: cannot stat '/home/mollusk/git/butter/void-mklive/tmp.E78xFIo6BT/void-host/usr/share/syslinux/libcom32.c32': No such file or directory
cp: cannot stat '/home/mollusk/git/butter/void-mklive/tmp.E78xFIo6BT/void-host/usr/share/syslinux/vesamenu.c32': No such file or directory
cp: cannot stat '/home/mollusk/git/butter/void-mklive/tmp.E78xFIo6BT/void-host/usr/share/syslinux/libutil.c32': No such file or directory
cp: cannot stat '/home/mollusk/git/butter/void-mklive/tmp.E78xFIo6BT/void-host/usr/share/syslinux/chain.c32': No such file or directory`
```
As a result, xorriso fails to complete and generates an error which in turn does not create the final image file.  

I am trying to find where the `$SYSLINUX_DATADIR` is set which is a variable used in `mklive.sh` but that variable does not seem to be originally set in the same file it is used.  If I can successfully locate this variable, I can change it and submit a pull request. Until then, if someone more familiar with the mklive scripts can sort this out quicker than I can, please do so as currently the system is broken.

EDIT: Found the SYSLINUX_DATADIR variable, it was in `mklive.sh` but closer to the bottom. Changed the variable and building a test image now.

EDIT2: The test image was successfully created. I am going to fork mklive and create a pull request.

Thanks

**Comment by the-maldridge** [comment]
git grep is your friend:

```
$ git grep SYSLINUX_DATADIR
mklive.sh.in:    cp -f "$SYSLINUX_DATADIR"/isolinux.bin "$ISOLINUX_DIR"
mklive.sh.in:    cp -f "$SYSLINUX_DATADIR"/ldlinux.c32 "$ISOLINUX_DIR"
mklive.sh.in:    cp -f "$SYSLINUX_DATADIR"/libcom32.c32 "$ISOLINUX_DIR"
mklive.sh.in:    cp -f "$SYSLINUX_DATADIR"/vesamenu.c32 "$ISOLINUX_DIR"
mklive.sh.in:    cp -f "$SYSLINUX_DATADIR"/libutil.c32 "$ISOLINUX_DIR"
mklive.sh.in:    cp -f "$SYSLINUX_DATADIR"/chain.c32 "$ISOLINUX_DIR"
mklive.sh.in:        -isohybrid-mbr "$SYSLINUX_DATADIR"/isohdpfx.bin \
mklive.sh.in:: ${SYSLINUX_DATADIR:="$VOIDHOSTDIR"/usr/share/syslinux}
```
Last item sets the default path.

**Comment by silvernode** [comment]
yeah I found it, submitted a pull request then realized that someone already did 3 days ago.
