### ISSUE TITLE
i686 live image fails to boot on ThinkPad T60.

### ISSUE THREAD

**Issue by head-gardener** [void-linux/void-mklive#320]
Booting from a USB stick with Void live image fails during an attempt to mount `/dev/loop1`.
Related dmesg messages:
```
EXT4-fs (loop1): mounting ext3 file system using the ext4 subsystem
EXT4-fs (loop1): INFO: recovery required on readonly filesystems
EXT4-fs (loop1): write access unavailable, cannot proceed (try mounting with noload)
```
Image file: `void-live-i686-20221001-base.iso`.
Same error occurred on both T60 i have access to.

**Comment by leahneukirchen** [comment]
Duplicate of https://github.com/void-linux/void-mklive/issues/292
