### ISSUE TITLE
[Question] unclear on how to build an image for Intel/AMD x86_64 for DigitalOcean

### ISSUE THREAD

**Issue by ibhagwan** [void-linux/void-mklive#321]
Hi,

I got to this repo from the VoidLinux website [sponsporship page](https://voidlinux.org/news/2021/09/sponsor-do-renew.html) which states:
```
Should you also want to run a Void Linux VM on DigitalOcean’s droplet service,
we provide tooling for generating Void Linux images in the mklive repository.
```

DigitalOcean does not support the `.iso` live image, I'm trying to create a `x86_64` (glibc) image for an Intel/AMD droplet with no success, it's somewhat hard to understand from the README what are the necessary steps to build a `.img` that isn't for ARM.

I looked through the issues with no success, only found this PR: https://github.com/void-linux/void-mklive/pull/140 which didn't help much as the templates seem to have undergone further modifications.

I succesfully created a rootfs with:
```
sudo ./mkrootfs.sh -r https://repo-default.voidlinux.org/current x86_64
```

But I'm not really sure where to go from here, reading #230 seems I can't make an `.img` file from the rootfs and that it's only for arm?

Further clarification would be very helpful and save me from having to reverse engineer the scripts :-)

**Comment by ibhagwan** [comment]
@the-maldridge, I see you're a maintainer in this repo as well as [shinit](https://github.com/the-maldridge/shinit), if I have an exisitng void-linux install with all the [prerequisites for DO](https://www.digitalocean.com/community/tutorials/how-to-create-an-image-of-your-linux-environment-and-launch-it-on-digitalocean), could that be a route to solving my issue (having a `.img` compatible with DO droplets)?

**Comment by Johnnynator** [comment]
Yes, the hashicorp packer scripts are what you are looking for.
You need to have at least `packer` and `qemu` installed to build an image.
If you working directory is in void-mklvie/packer you can build them like this:

`packer build -only="cloud-generic-x86_64*" hcl2`

**Comment by ibhagwan** [comment]
Ty @Johnnynator! will this generate a digital ocean compatible `.img` custom image?

Also any idea why the scripts fail with `Operation not permitted` when trying to access the void linux repo?
![image](https://user-images.githubusercontent.com/59988195/220740291-c9d0ffcf-0f11-471e-8c2b-c887a9734530.png)

**Comment by ibhagwan** [comment]
This seems to be an issue with the image linked in the hcl packer builds, the certificates for xbps are no longer valid and I can't seem to hack my way through it with `SSL_NO_VERIFY_PEER=1`, any idea how to proceed with this?

**Comment by classabbyamp** [comment]
should work now if you pull: 083c271f5647c1c327be8f02b150e91deb2267d6

**Comment by ibhagwan** [comment]
I thought about changing the ISO and the checksum myself but I was under the impression this was a "special build" due to [the note in the builds folder](https://repo-default.voidlinux.org/live/20200722/READ_THIS_NOTE.txt)

Anyways tyvm @classabbyamp it worked.

![image](https://user-images.githubusercontent.com/59988195/220793886-6b571daf-9f86-49db-8403-6b11fda200f7.png)

I'm not sure yet if this is this is the expected output, can you confirm this is what to expect?
```
void-mklive/packer on  master [?] ❯ la cloud-generic-x86_64
.rw-r--r-- 1.7G root root 2023-02-22 16:14 voidlinux-x86_64
void-mklive/packer on  master [?] ❯ la cloud-generic-x86_64-musl
.rw-r--r-- 1.7G root root 2023-02-22 16:13 voidlinux-x86_64-musl
```
Are the above valid images or is anything missing?

I renamed the `x86_64` file to `.img` and tried to uploade it to Digital Ocean but it still fails with an empty error message, do you have any experience with that by any chance?
