### ISSUE TITLE
installer for x86_64 architecture (glibc) fails to create user account

### ISSUE THREAD

**Issue by pellea72** [void-linux/void-mklive#350]
After going through the installation in the x86_64 installer, pulling from online repositories, I could only log in as root. The user account that was supposedly created during the installation did not exist (not listed in /etc/passwd or /etc/group), nor was there a directory  in /home. I installed several times in the same day, and all three times I had to manually create my user.

During the installation I did not change the default groups that the user would be assigned to. I definitely entered a name and a password (and confirmation password).

I did not have this problem after installing the MUSL version before switching to the glibc version.

For what it's worth, I installed on a Dell Inspiron 3880 using the void-live-x86_64-2022-10-01-base.iso.

**Comment by classabbyamp** [comment]
known issue, already fixed. https://github.com/void-linux/void-mklive/pull/319

as a workaround until the next iso (very soon!), you can do a local install instead of a network install

**Comment by pellea72** [comment]
Thank you for the quick response. I didn´t think to check closed issues.
