### ISSUE TITLE
lightdm keyboard layout issue

### ISSUE THREAD

**Issue by etech-dev** [void-linux/void-mklive#353]
Hi,
I like the installer very much and studied it's very interesting code but there's a small annoying issue (for the average user wanting to try Void).
When rebooting after the install is done lightdm still has the 'en_US' keyboard layout and users from non english spoken countries (as for me - french azerty kb layout) can't log in (user login and/or password).
Everything is allright for Xfce but not for lightdm. So I built an ISO with void-mklive for my language and am still looking for a solution for all languages. If I can help or give more precisions then I'll do. Thanks.

**Comment by etech-dev** [comment]
Thank you classabbyamp, I'll try this solution and let you know.

**Comment by etech-dev** [comment]
Hi,
I tried this solution and it doesn't work. As far as I remember I already tried this yesterday => no way!
So I go on searching for a solution as it would good for users not to be disappointed by our distro of choice on the first reboot ;o) 
By the way do you know who is developing the installer (installer.sh) for the distribution so that we can exchange on the subject and try to solve the issue? Thank you.

**Comment by classabbyamp** [comment]
did you restart the lightdm service after changing the configuration?

**Comment by etech-dev** [comment]
Yes, I rebooted the test machine. I'll try again as it's late now and let you know. Thanks again.

**Comment by classabbyamp** [comment]
this won't change the keyboard layout but will put a menu in the top right that lets you select your layout. there's also [this possible solution](https://wiki.archlinux.org/title/LightDM#Keymap) that will hard-code the keymap
