### ISSUE TITLE
sshd service enabled on local-installed system

### ISSUE THREAD

**Issue by Stidgit** [void-linux/void-mklive#355]
Why exactly would this be ON by default? I know the system is reliant on OpenSSH but it being open doesn't contribute to it in any positive way.

**Comment by classabbyamp** [comment]
I'm unsure if this is a regression in 20230628 but it should probably not be there. I expect this will be fixed by larger refactors planned before the next release

**Comment by Duncaen** [comment]
https://github.com/void-linux/void-mklive/issues/40 this has always been the case for the live image because there was some opposition to disabling it by default.

**Comment by classabbyamp** [comment]
this is related to [this thread](https://old.reddit.com/r/voidlinux/comments/16ia683/is_it_normal_for_ssh_to_be_open_by_default/) where sshd is running on the installed system too

my thoughts are basically that #333 and adding a service enablement page to the installer will ensure that this will only happen when the user wants it to

**Comment by Vaelatern** [comment]
I continue to oppose disabling ssh in the live image. I do support keeping SSH disabled in installed systems until a user deliberately wants it activated (it's the first thing I enable before rebooting from the installer, on my manual installs).

**Comment by classabbyamp** [comment]
updated title to be more specific about the unexpected behaviour. SSH enablement in the live environment itself was never in question here

**Comment by Duncaen** [comment]
On installed systems it has a password that is not fixed. I really don't see why this couldn't be opt in with a command line. The argument that you have to trust the network is annoying, I don't control the vultr or digital ocean or whatever setup.

**Comment by Stidgit** [comment]
> I continue to oppose disabling ssh in the live image. I do support keeping SSH disabled in installed systems until a user deliberately wants it activated (it's the first thing I enable before rebooting from the installer, on my manual installs).

Abby corrected the title. The question in mind was about SSH being enabled on an installed system, not a live image. My apologies.

**Comment by vincele** [comment]
We may even allow root login via ssh for the live image, because it is not hidden very far away anyways.
I use log via ssh on hosts that have no console.

**Comment by classabbyamp** [comment]
there is no reason to allow root login via ssh
