### ISSUE TITLE
broadcom-wl-dkms not working in live image

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-mklive#358]
I have an old HP Probook 4310s, with a broadcom wifi card.

I created a live iso with `broadcom-wl-dkms` package (and `linux*-headers` too).

When I boot to the iso I do not have wifi available, (`broadcom-wl-dkms` is installed).
When I perform the installation to the drive and boot it, wifi is still not available.

For wifi to work I had to force a reinstall of the `broadcom-wl-dkms` package.

**Comment by abenson** [comment]
> When I boot to the iso I do not have wifi available, (broadcom-wl-dkms is installed).

Did you try manually loading the `wl` driver? `modprobe wl`

Also, you're sure the dkms module built and it was loaded into the `initramfs` the live image is using?

>  When I perform the installation to the drive and boot it, wifi is still not available.

Just verifying you did a local install?

**Comment by Eloitor** [comment]
Thanks for the quick response,

`modprobe: FATAL: Module wl not found in directory /lib/modules/6.5.3_1`

Maybe it didn't built... Should it be built automatically by having those packages installed?
A dirty hack would be to manually add the compiled module to the right place in the iso...

Yes, I did a local install.

**Comment by classabbyamp** [comment]
Did you see the dkms module build messages in the log when generating the image?

**Comment by Eloitor** [comment]
I didn't pay attention... tomorrow I'll build it again and log the messages.

**Comment by Eloitor** [comment]
It didn't build the dkms module...

```bash
export PACKAGE_LIST="broadcom-wl-dkms dialog cryptsetup lvm2 mdadm
 grub-x86_64-efi chrony dbus elogind gdm NetworkManager polkit-gnome vsv xorg gnome"
export XBPS_REPOSITORY="--repository=https://repo-fi.voidlinux.org/current --repository=repo-x86"
export SERVICE_LIST="chronyd dbus elogind NetworkManager polkitd gdm"
./mklive.sh -I "include-x86" -o "Test_1.iso" > Test_1.log
```

`repo-x86` contains the `broadcom-wl-dkms` and `include-x86` has the `/usr/bin/void-installer` 

[Test_1.log](https://github.com/void-linux/void-mklive/files/12672964/Test_1.log)

**Comment by Kerrnel** [comment]
Confirm that wl.so not installed in /lib/modules as expected on a MacBook Pro - Musl and LibC

**Comment by classabbyamp** [comment]
this is a funny bug. dkms makes `/var/lib/dkms` during xbps's package configuration, so if a dkms module comes *before dkms alphabetically*, it fails `dkms add` with `Error! No write access to DKMS tree at /var/lib/dkms`... because `/var/lib/dkms` doesn't exist. this doesn't usually happen for normal usage because `xbps-install -U; xbps-reconfigure -a` is not common.

**Comment by Eloitor** [comment]
Thank you! I'll be able to try it next week
