### ISSUE TITLE
console=ttyS0 doesn't enable agetty-ttyS0

### ISSUE THREAD

**Issue by ZyxerZyxani** [void-linux/void-mklive#362]
I tried to install to a VM. It is a minimal VM with only serial port to connect with. Doing console=ttyS0 doesn't seem to work to enable the service in the live image. I get grub in ttyS0 and can connect, but after selecting the first option it just goes to black and I can't type anything.

**Comment by leahneukirchen** [comment]
I think `dracut/vmklive/getty-serial.sh` should enable that?

Works for me in qemu with https://repo-default.voidlinux.org/live/current/void-live-x86_64-20230628-base.iso

**Comment by classabbyamp** [comment]
also cannot reproduce with that ISO in virt-manager
