### ISSUE TITLE
/boot partition too small on Raspberry Pi live image

### ISSUE THREAD

**Issue by bsduck** [void-linux/void-mklive#363]
Hello,

The aarch64 live image provided for the Raspberry Pi (void-rpi-aarch64-20230628.img) comes with a tiny /boot partition of 64MB.

This is too small in my opinion. For example, installing a second kernel is not possible because of the lack of space. I wanted to install linux6.6 in addition to the installed 6.1 kernel but xbps-install couldn't complete because /boot was full.

It is also not possible to extend it because it is located at the beginning of the disk and just after that comes the root partition. So the only way to get a more reasonably sized /boot is to create another bigger partition elsewhere on the disk, move the contents there and delete the original one.

I understand the wish to keep it small, but making it for example 256MB instead of 64MB wouldn't make much difference in terms of disk space used (I don't think many people will flash the .img to a microSD card smaller than 8GB nowadays), but would be a huge improvement in convenience for most users.

**Comment by classabbyamp** [comment]
the `linux6.6` package will not work with raspberry pi; they need a [special non-mainline kernel](https://github.com/raspberrypi/linux).

It is possible to move the root partition then expand the boot partition. Alternatively, you can customise the exact partition layout by using `mkimage.sh` or by doing a PLATFORMFS-based install.

All that said, I'd be open to bumping the default size.
