### ISSUE TITLE
installer saves partition layout after exit

### ISSUE THREAD

**Issue by jaminW55** [void-linux/void-mklive#367]
I have recently used to the most up to date installer: void-live-x86_64-musl-20230628-base.iso, to install Void on my Thinkpad470.

The installer completed, and ran, but after restart it was found to boot partition was created and the install seemed to be incomplete. I followed multiple guides and troubleshooting posts after running into this issue, but none helped correct the issue.

In the end I tested features with the cfdisc and noticed the installer seemed to save changed done within the installer even after exiting or removing the install medium, USB stick, and would even run. Deciding that cfdisc was likely the issue, and knowing it would save any changes if opened once, I restarted, and did everything in the installer except for the partitions. For this, I exited the installer, set the partitions manually, using fdisc, and then ran. This produced a working system, but it turned Void's normal 3 minutes install process into over an hour. I've noticed many other people having issues with the installer and I believe this is related to the partition feature incorrectly creating and writing partitions.

EDIT: I would like to add I was not once given the option to choose between: gpt, dos, etc. I did attempt to flash the installer more than once and on more than one USB, and this remained the case.

**Comment by classabbyamp** [comment]
> I would like to add I was not once given the option to choose between: gpt, dos, etc.

this would suggest your disk already had a partition table, so cfdisk did not prompt you to create one. `wipefs` would be able to remove that for you (or `cfdisk -z`)

**Comment by classabbyamp** [comment]
>  the installer seemed to save changed done within the installer even after exiting or removing the install medium, USB stick, and would even run

if you did not reboot, the installer would have saved the settings to a file in `/tmp`. If you did reboot, then the saved changes you saw are probably from writing the partition table to disk in cfdisk.

**Comment by jaminW55** [comment]
> > I would like to add I was not once given the option to choose between: gpt, dos, etc.
> 
> this would suggest your disk already had a partition table, so cfdisk did not prompt you to create one. `wipefs` would be able to remove that for you (or `cfdisk -z`)

But should it not anyway? Backing out of an installer to run commands and then re-entering is a bit strange. If I find this issue again, I will recall, but should the cfdisc not override existing partitions?

**Comment by jaminW55** [comment]
> > the installer seemed to save changed done within the installer even after exiting or removing the install medium, USB stick, and would even run
> 
> if you did not reboot, the installer would have saved the settings to a file in `/tmp`. If you did reboot, then the saved changes you saw are probably from writing the partition table to disk in cfdisk.

The changes did not persist between reboot.

**Comment by classabbyamp** [comment]
> But should it not anyway? Backing out of an installer to run commands and then re-entering is a bit strange.

This has been a requested feature in the past, so yes, it should, it seems

> If I find this issue again, I will recall, but should the cfdisc not override existing partitions?

it should not, as some people don't want their disks erased before installing void (dual boot, for example)

**Comment by jaminW55** [comment]
> it should not, as some people don't want their disks erased before installing void (dual boot, for example)

So, is the solution for now to always run the above commands before entering the void-installer? 

Will future iterations fix this issue?

**Comment by classabbyamp** [comment]
You'll have to give more info about what the problem is, because from what you've said so far I don't see an issue

**Comment by jaminW55** [comment]
To abridge the issue:
1. Boot from Installer USB
2. Run Void Installer as root
3. Go through the installer
4. Installer failed to create bootable system
5. Persisted across multiple attempts

**Comment by jaminW55** [comment]
In relation to this issue, I plan to install on my desktop and dual boot with Arch.
Would the recommend course of action be to wipe the disk beforehand?

**Comment by classabbyamp** [comment]
i'm not sure why you would need to or want to wipe the disk

**Comment by jaminW55** [comment]
When I run a cfdisc and write my partitions, select root, boot, etc.
I would expect it to wipe and write the drive as set in the cfdisc, but it seems to not be functioning as such.

Should the installer not simply install the OS on the disk, following the partitions as set by the cfdisc?

**Comment by classabbyamp** [comment]
if you wiped and wrote the partition table to the disk in cfdisk it will do that. all the installer does is shell out to cfdisk, then read the partition tables in the filesystem configuration section.

**Comment by jaminW55** [comment]
Yes. This was the core toot of my issue. 

The cfdisc, no matter how many attempts or what it indicated, would not properly install. 
It simply ran the installer with said settings, but did not actually install or create a bootable system.

Only when I manually created an fstab, saved, and did not open the drive partition option within the installer, did the system actually install.
