### ISSUE TITLE
util-linux 2.39 regression: overlayfs root fails to remount ro 

### ISSUE THREAD

**Issue by sdbtools** [void-linux/void-mklive#369]
Steps to reproduce:
```
sudo ./build-x86-images.sh -- -v linux6.7
```
Result:
```
Writing to 'stdio:void-live-x86_64-20240222-base.iso' completed successfully.

Created /xxx/void-mklive/void-live-x86_64-20240222-base.iso (1.1G) successfully.
umount: /xxx/void-mklive/tmp.t1PsYOZ1A5/image/rootfs/sys: not found
ERROR: failed to unmount /xxx/void-mklive/tmp.t1PsYOZ1A5/image/rootfs/sys/
```
Version:
```
$ ./build-x86-images.sh -V
build-x86-images.sh 0.25 63c1152
```
I cannot boot created ISO (kernel 6.7.5). rootfs won't mount.

**Comment by classabbyamp** [comment]
the error during image generation itself is spurious, that's just a missing check in the cleanup (9708d22)

can't repro the mount failure with [images generated on 2024-02-17](https://devspace.voidlinux.org/abby/live/void-live-20240217/)

can repro the mount failure with an image on 6.6 generated today (`make live-iso-all LIVE_ARCHS="x86_64" LIVE_FLAVORS="base"`)

the most probable cause is either the util-linux update or the kernel update, IMO

**Comment by classabbyamp** [comment]
can confirm, reverting the latest `util-linux` and `util-linux-common` updates fixed it

**Comment by classabbyamp** [comment]
for future reference, the exact error is:
```
=> Remounting rootfs read-only...
mount: /: mount point not mounted or bad option.
       dmesg(1) may have more information after failed mount system call.
```
what's failing appears to be `mount -o remount,ro /` in `/etc/runit/core-services/03-filesystems.sh`

**Comment by classabbyamp** [comment]
possibly related: https://github.com/util-linux/util-linux/issues/2528
