### ISSUE TITLE
autoinstaller default swapsize exceeds disk size if there's less disk than memory

### ISSUE THREAD

**Issue by nilium** [void-linux/void-mklive#37]
Title summarizes it, but the autoinstaller's default swapsize can cause sfdisk to fail when the target disk is smaller than the amount of memory. In particular, I ran into this when provisioning an R640 with an approximately 200gb root disk and 384gb of memory.

I need to work on a patch to set a reasonable upper bound on that (i.e., smaller than disk size) so that the installer doesn't croak. Until I have time for that and for any readers wondering, the solution is to just set your own swapsize.

Relevant line: https://github.com/void-linux/void-mklive/blob/master/dracut/autoinstaller/install.sh#L192

**Comment by the-maldridge** [comment]
I'm going to close this as out of scope, as the autoinstaller should probably be overridden for cases where the automagic math is wrong.
