### ISSUE TITLE
Unable to install void linux

### ISSUE THREAD

**Issue by Yakumo-Yukari** [void-linux/void-mklive#376]
![IMG_20240425_081256](https://github.com/void-linux/void-docs/assets/12076232/d5a7f420-36cf-4380-ae28-111f67d646b5)
![IMG_20240425_081822](https://github.com/void-linux/void-docs/assets/12076232/8a8f0bfc-bbc2-4538-8388-de21a1466958)

When installing, selecting UEFI USB flash drive entry will keep getting stuck at the logo

![IMG_20240425_081359](https://github.com/void-linux/void-docs/assets/12076232/98d2144e-ac07-4e6a-8d13-40b04e156dcc)
![IMG_20240425_081930](https://github.com/void-linux/void-docs/assets/12076232/eb88a7d2-d936-4e84-972d-45779c891aa5)

If you choose to enter from a USB flash drive, you will be stuck at booting the kernel.

iso ：void-live-i686-20240314-base.iso

**Comment by classabbyamp** [comment]
you say you're using the i686 iso but the picture shows x86_64? what cpu/gpu is this?

**Comment by classabbyamp** [comment]
1. use the x86_64 iso, that's a 64bit processor
2. you might need follow the instructions here: https://old.reddit.com/r/voidlinux/comments/1cc2xe5/to_those_who_are_stuck_on_loading_initial_ramfs/
