### ISSUE TITLE
Assign mount point for partitions without formatting

### ISSUE THREAD

**Issue by vitormmatos** [void-linux/void-mklive#378]
Assigning partitions without formatting would be useful for re-using a home partition. It would be great for when using multiple linux distros. (Arch does this btw). Also, swap usually is not needed to be formatted.

**Comment by classabbyamp** [comment]
this already exists in the installer, it's a yes/no prompt in the partition assignment section

**Comment by vitormmatos** [comment]
Even after I select no, when confirming to install, it gives me a warning saying the selected partitions will be formatted.
I tried it with x86_64 musl latest version

**Comment by classabbyamp** [comment]
it says "WARNING: data on partitions will be COMPLETELY DESTROYED **for new filesystems**." is it saying `NEW FILESYSTEM:` in the summary for the home partition?

**Comment by vitormmatos** [comment]
Pardon me, seems I misread it, my bad.
