### ISSUE TITLE
Pinephone image does not boot when resized

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-mklive#380]
I'm generating a image for the pinephone:
```
cd void-mklive
sudo ./mkrootfs.sh aarch64
sudo ./mkplatformfs.sh pinephone void-aarch64-ROOTFS-$(date +%Y%m%d).tar.xz
sudo ./mkimage.sh void-pinephone-PLATFORMFS-$(date +%Y%m%d).tar.xz
```

After that, I flash the .img to the pinephone and it boots. But if I use gparted on my computer to resize the second partition to use all the space on the SD card, it no longer boots. I also tried the whole process on the eMMC.

I also tried with a new version of pinephone-uboot https://github.com/void-linux/void-packages/pull/51217

**Comment by classabbyamp** [comment]
is this using the latest commit with the growpart core-service added in #379? if so, can you also try building at 5b6ef65055457e8c984afd2218ffa585639f116c?

**Comment by classabbyamp** [comment]
also, what do you mean by not booting? what *exact* symptoms do you see?

**Comment by Eloitor** [comment]
I was pretty sure I was building from the latest commit, but I'm not sure since the image was 2Gb and this was changed in the last commit. I'll try again.

I tried building with https://github.com/void-linux/void-mklive/commit/5b6ef65055457e8c984afd2218ffa585639f116c the same happens. I can boot into it without problems. It asks me login and password and I can use it.

After resizing using gparted, it does not boot: I see a very short green led and the screen remains black.

**Comment by Eloitor** [comment]
The Green led lasts 2-3 seconds, stops and then it is green again for a fraction of a second.

**Comment by classabbyamp** [comment]
thrn it might be gparted to blame, what if you change it with cfdisk/resize2fs manually (this is basically what the new growpart thing does, so maybe try that)

fwiw i don't have a pinephone so I can't test anything to reproduce this

**Comment by Eloitor** [comment]
I created a new image using the latest commit and it resized automatically to the full storage!

**Comment by classabbyamp** [comment]
awesome, glad to see it works on more than just the raspberry pi i tested with
