### ISSUE TITLE
installer bug: user with short password is not created, and not explained

### ISSUE THREAD

**Issue by shula** [void-linux/void-mklive#382]
during installation, there's an option to create a regular user (and password)
The interface accepts short passwords without errors.
Later, in the "install" step, the installer complains there are no users defined.
Although I clearly defined a user (even multiple times).

Only when I created a long(er) password, the instsaller didn't report the problem.

This must be either explained, or give an explicity error message.

**Comment by abenson** [comment]
I just ran through the installer, set the password for the user to the single character 'a' and it worked fine.

**Comment by classabbyamp** [comment]
could not reproduce either
