### ISSUE TITLE
duplicate timezone entry for Nepal in installer (Kathmandu & Katmandu)

### ISSUE THREAD

**Issue by sudanchapagain** [void-linux/void-mklive#385]
Sorry if i am opening this issue in the wrong place. Installer is where i faced the issue so opening this issue here.

While i was looking into Void linux, the installer had two entries for Nepal's timezone which is identified by capital city's name Kathmandu. The two entries are Katmandu & Kathmandu. I assume tzdata is being used but as of 2024b's data Katmandu is a link/alias to Kathmandu. I tried to look into this but i simply couldn't due to my inexperience and part incompetence. Could this be looked into?

**Comment by the-maldridge** [comment]
This is plausibly one of the many issues in tzdata around the time the last image set was made.  @classabbyamp do you know if the current version of tzdata resolves that?

**Comment by sgn** [comment]
> I assume tzdata is being used but as of 2024b's data

Yes!

> Katmandu is a link/alias to Kathmandu

Yes

> The two entries are Katmandu & Kathmandu.

Yes, too. Because, I choose to ship `backward` timezone as well. Why?

- Is there any problem with shipping both?
  -> No!
- Is there any problem with not shipping both?
  -> Yes! Because:
    - someone may have set `Asia/Katmandu` as their timezone, and now they have broken time system.
    - Same with `Asia/Kuala_Lumpur`, which is now a link to `Asia/Singapore`
    - `Europe/Nicosia`, yes people think that Cyprus is European, but no, Cyprus is a country in Asia.
    - `Atlantic/Reykjavik`: Ireland need to use `Africa/Abidjan` without backward

**Comment by classabbyamp** [comment]
also `America/Montreal -> America/Toronto`, which i prefer for reasons :P

**Comment by sudanchapagain** [comment]
@sgn i see. thank you, it does make sense now ig.

> Atlantic/Reykjavik: Ireland need to use Africa/Abidjan without backward

*iceland?

**Comment by sgn** [comment]
> also `America/Montreal` (points to `America/Toronto`), which i prefer for reasons :P

French speakers prefer Montreal I guess.
