### ISSUE TITLE
autoinstaller enable

### ISSUE THREAD

**Issue by SirMetathyst** [void-linux/void-mklive#39]
Hello, I want to have a void linux iso automatically install itself rather than going through the void-installer. I found https://github.com/void-linux/void-mklive/blob/master/dracut/autoinstaller/install.sh which looks like what I want. Is this something that can be run instead of void-installer? How can I enable it? Or do I just have to create my own void-installer.sh script instead?

**Comment by the-maldridge** [comment]
The autoinstaller is very limited in what it can do, and effectively only builds MBR bootable unencrypted installs.  If that's what you want, then you can append "auto auto.url=<url>" to the kernel command line to enable the autoinstaller.  This will wipe whatever machine you try it on so make sure that's what you want.  The URL points to a configuration file which has the same format as the one in the repo, but with the options you choose.

**Comment by SirMetathyst** [comment]
That's fine for me, thank you!
