### ISSUE TITLE
void-installer: Any plans for easy full-disk encryption options?

### ISSUE THREAD

**Issue by zayuim** [void-linux/void-mklive#53]
I feel that the biggest thing missing from the void installation is full-disk encryption setup.

Right now you have to manually set it up outside of the installer, and you must do a network install. I like how Void has DE's setup by default on the live images and would prefer to have those installed over the network which only has a tty.

So is there any plans to include this as an option, or is there anyway to setup full-disk encryption and install the live image?

**Comment by Duncaen** [comment]
I don't think there are any plans, I think there are too many different ways of doing it and too many things that can go wrong.

The desktop environments are effectively just installing the packages and that is it, the live images provide no other configuration than enabling a few services.

And you are also not forced to do a network installation if you setup a chroot, you can do the same thing the installer would do and just copy the whole rootfs into the chroot and remove some files.

**Comment by aeosynth** [comment]
> you can do the same thing the installer would do and just copy the whole rootfs into the chroot and remove some files

could this be added to the handbook?

**Comment by atweiden** [comment]
> I feel that the biggest thing missing from the void installation is full-disk encryption setup.

@zayuim I made an installer that might be to your liking: https://github.com/atweiden/voidvault

**Comment by the-maldridge** [comment]
@zayuim the short answer is no, there are no plans for this in the short term as it is not in the spirit of Void, which is you should understand why your system is doing the things it does.  If you want an opinionated installer that can setup your system without requiring your review, I would for sure check out voidvault as linked above.

@aeosynth see void-linux/void-docs#97.
