### ISSUE TITLE
void-installer: "Settings" button is misleading

### ISSUE THREAD

**Issue by joshuakraemer** [void-linux/void-mklive#6]
The "Settings" button in the Void Linux installer utility leads to a view of the chosen installation settings. I think the term "Settings" is misleading for this purpose (I was expecting a dialog with options to configure the installer). Please consider changing it to "Review settings" or something similar.

**Comment by classabbyamp** [comment]
it may be a bit terse, but once you open it, the title gives a hint. I think making the button text longer would make it take up too much space
