### ISSUE TITLE
Fat DVD releases?

### ISSUE THREAD

**Issue by rubyFeedback** [void-linux/void-mklive#68]
Hello void folks,

Sorry if this is not a good area for issue discussion but I would still like to file it, if it is ok.

We can download voidlinux here:

https://voidlinux.org/download/

We have flavours such as:

    Enlightenment
    Cinnamon
    LXDE
    LXQT
    MATE
    XFCE

I would like to have a fat dvd, that is, a large .iso that I could just batch-install. If anyone knows the DVD of slackware, that is exactly what I would love to have. I don't care if parts of it become outdated and it does not have to be maintained a lot, e. g. one release of that per year would be perfectly fine, based on the other flavours.

Why would I want a fat DVD? Mostly due to convenience. I don't like post-installation routines that take long; I'd really love to just install what is useful and come back to the computer when this is all done. Saves me lots of time and problems lateron.

I am not sure how much work this would be; ideally the existing flavours could just be combined as-is, but I am not sure how simple that is. I guess the more important question here is whether voidlinux would even want to offer a big DVD but I'd think it would be for extra flexibility, for those who'd like it. On distrowatch, if you look around, most releases are quite large by now - voidlinux on the other hand does not have a large .iso right now.

Thank you for reading - feel free to close this issue at any moment in time.

**Comment by the-maldridge** [comment]
My personal stance is that there are too many flavors already.  Its a pain to build them and takes several hours during which for asinine reasons we need to not be building anything.  I'll leave this open and it can be figured out in here, but from what you suggest it sounds like you want to do a lot of installs, for which PXE and the autoinstaller are really better suited.

**Comment by Vaelatern** [comment]
The only flavors we have are the basic ones for advertising that we have various DEs and WMs, and then we have the single image for everybody else.

I encourage you to roll your own variety of DVD, the scripts are all in this repo and people on IRC can probably help if you get stuck, but we will probably not distribute another flavor.

**Comment by the-maldridge** [comment]
In light of #71, I'm going to close this.  If anyone wants to add a fat flavor to the build-x86-images script they're welcome to, but Void won't ship the ISO.  Just because other distros need to go on a diet doesn't mean we're going to ignore our principals of small, efficient, and fast.
