### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by mquarneti** [void-linux/void-mklive#7]
```bash
sudo ./mklive.sh -a x84_64-musl -k it
```
This build requires liblz4, the VirtualBox installation I have don't have this package installed by default.

Should liblz4 be added to the dependencies in the README.md?

**Comment by lyn1337** [comment]
Was also missing squashfs-tools pkg, resulting in an .so missing error in the later creation steps.

**Comment by KalleDK** [comment]
and to nitpick make is also a dependency.

Did a clean install via the void-installer fetched the repo installed qemu-user-static and verified xbps.

Tried to run make and discovered it's not i nthe base install (which i find good !) but it then should be a dependency imho.

**Comment by the-maldridge** [comment]
This was resolved in the referenced PR.
