### ISSUE TITLE
Reducing the number of images provided officially.

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-mklive#71]
Currently shipping a new set of images requires a period of time where all builds can be stopped, and where everything can generally be assumed to be working.  This is all for not a huge amount of gain.  To ease this and to make it easier to release updated images on a more regular schedule, I'd like to reduce the number of images that are provided.  The others will remain in the system, but won't be generated by default.

I propose removing the following images:
  * All GCP Images
  * All usbarmory filesystems
  * The enlightenment images (all architectures)
  * The LXQT images (all architectures)
  * The MATE images (all architectures)
  * All i686 images with the exception of the xfce4 image and the no-DE image.
  * The x86_64 and i686 filesystems

Dropping the above images would reduce the number of images by 18, leaving 30 images.  This still shows the versatility and adaptability of Void, but does so without impeding the release cadence for the ISOs.

I personally would also like to see the cubieboard2 and odroid-c2 images dropped from the provided set, which would bring us down to 26 provided images.

I intend to spin new images this coming weekend, so I'd like to get this resolved before then.

**Comment by leahneukirchen** [comment]
I think the filesystems are almost free, but :+1: else.

**Comment by the-maldridge** [comment]
Its really because they're almost free that I want to drop them.  They can be easily generated later when they're going to be used rather than being generated and then sitting and becoming stale.  A lot of our images become incredibly stale during the time that they haven't been downloaded yet.

**Comment by the-maldridge** [comment]
Suggested images have been dropped.
