### ISSUE TITLE
Incorrect partition table instructions

### ISSUE THREAD

**Issue by gsruff** [void-linux/void-mklive#72]
From what I understand, GPT disklabels do not use flags like MBR disks. The warning before partitioning in the installer states "For EFI systems GPT is mandatory and a FAT32 partition with at least 100MB must be created with the TOGGLE 'boot', this will be used as EFI System Partition. This partition must have mountpoint as '/boot/efi'."

Setting this "boot" flag on a GPT disk partition using cfdisk is not possible. Setting the partition type as EFI System in cfdisk establishes that this is the boot partition.

![image](https://user-images.githubusercontent.com/41163946/58354132-8373fe80-7e3e-11e9-8e7f-eddca548b068.png)

**Comment by the-maldridge** [comment]
While I agree with you that these instructions are probably wrong, I am aware of at least 2 BIOS/UEFI implementations that are flawed and require the appropriate location on disk contain the right values even when booting in UEFI mode.
