### ISSUE TITLE
Cannot create base live image from this repo

### ISSUE THREAD

**Issue by hectormonacci** [void-linux/void-mklive#73]
Today I successfully cloned https://github.com/void-linux/void-mklive, did `cd void-mklive`, and then successfully issued `make`. No errors were reported.

I read the short help by issuing `./build-x86-images.sh -h`

Then I tried to prepare a base live image thus: 

`./build-x86-images.sh -b base`

**But it got stuck at step [4/9]**. It complains this way before dying: _Cannot install a hook (/usr/lib/dracut/modules.d/01vmklive/copy-initramfs.sh) that does not exist._

The whole output can be seen here: https://pastebin.com/tWa2WBfW

Something's broken here I suppose?

**Comment by the-maldridge** [comment]
Resolved as part of 6ce4732
