### ISSUE TITLE
sh is not as good in math as bash is

### ISSUE THREAD

**Issue by hectormonacci** [void-linux/void-mklive#75]
On line 353 of file mklive.sh.in you have this bashism:

`[ -n "${INCLUDE_DIRECTORY}" ] && ((STEP_COUNT=STEP_COUNT+1))`

Since shebang line states this script gets executed by /bin/sh, that math simply doesn't happen. Just change the line to this:

`[ -n "${INCLUDE_DIRECTORY}" ] && STEP_COUNT=10`

**Comment by Vaelatern** [comment]
I like the solution in #76.
