### ISSUE TITLE
Problems with installation in case of unavailability of the main repository.

### ISSUE THREAD

**Issue by hhrhhr** [void-linux/void-mklive#80]
During installation, the main repository URL is used to check network availability. The same URL is the only one for a network installation. However, in case of problems in the main repository, the network check fails and the network installation is not possible.

Suggestion: to test the availability of a network, use several third-party addresses (google.com, kernel.org, ntp.org ...); additionally specify several backup repositories in the xbps configuration.

**Comment by the-maldridge** [comment]
XBPS does not have a concept of a "backup repository" and rather than specifying a 3rd party site who have not approved our use of them as a status check host, it makes more sense to pull out the gateway address of the linked connection and see if we can route as far as that.  If you can get to the local router, anything beyond that is not a void problem.

**Comment by hhrhhr** [comment]
>_not have a concept of a "backup repository"_

Really? https://github.com/void-linux/xbps/issues/148

> it makes more sense to pull out the gateway address of the linked connection

No. If http://alpha.de.repo.voidlinux.org is down, then network setup step fail with something like `ERROR: DHCP request failed for wlp1s0. Check /dev/tty8 for errors.`. At the same time, `ping (google.com|kernel.org|ntp.org|...)` from the second console works fine.

**Comment by Vaelatern** [comment]
Why not manually list repositories on the installation line?

I see the problem, but think the answer lies at the user's fingertips.

**Comment by classabbyamp** [comment]
this is solved by adding mirror selection to the installer (though the network test does try to grab a file from repo-default only)

#318
