### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by bh90210** [void-linux/void-mklive#84]
hello there,

I am trying to setup a docker container for testing purposes and I am getting this error
```
docker run --rm -it -t void-test /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
``` 

this is my Dockerfile (`docker build -t void-test .`)
```dockerfile
FROM voidlinux/voidlinux-musl:latest
RUN xbps-install -Syu
```

does anyone know why?

**Comment by Duncaen** [comment]
bash is not part of `base-minimal`, which is used for docker containers, they come with dash only as `/bin/sh`.

**Comment by bh90210** [comment]
uh, thanks! got it working :)

**Comment by Vaelatern** [comment]
Ah cool, did not know, thought we depended too much on bash.
