### ISSUE TITLE
masterdir docker images are stale

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-mklive#91]
The docker images for the masterdirs used by travis are stale and updating the bootstrap causes a couple thousand lines of error messages, making it really a pain to read people's error logs. I made new images myself to test them and they worked fine at first glance.

Just to share my testing, I made 3 new images with the following method (and the patch from the PR to let alpine talk to our mirrors):
```
docker build --build-arg BASEPKG=base-chroot --build-arg ARCH=x86_64-musl .
```
And tested them on a branch on my repo:
https://travis-ci.org/bobertlo/void-packages/builds/601895748

**Comment by xtraeme** [comment]
Finally!!!

**Comment by the-maldridge** [comment]
Images are no longer stale.  As for adjusting the version used in CI, consult void-linux/void-packages#15750
