### ISSUE TITLE
Please add ntfs-3g by default for live images

### ISSUE THREAD

**Issue by anaggh** [void-linux/void-mklive#95]
-> User installs live image
-> Boots into it. Tries to copy their previous backup from external hdd.
-> User cannot read/write from hdd.

**Comment by the-maldridge** [comment]
The idea of the live images is to provide a place to do an installation, or in the case of the graphical images to try out the environment.  They are not designed for general case work or for accessing external drives, which from a handful of sources are recommended to be exfat anyway.

You may be interested in [hrmpf](https://github.com/leahneukirchen/hrmpf), which includes more drivers, more utilities, and sounds like its better suited to your use case.
