### ISSUE TITLE
void-installer: file system setup

### ISSUE THREAD

**Issue by msiism** [void-linux/void-mklive#98]
There's a bit of a problem with one of the file system setup dialogs in `void-installer`, namely that said dialog doesn't reflect the user's choice of file system for a given partition. I took some pictures to document the problem when I installed Void on a laptop recently and created a little photo story for your information. Note that the ext3 file system the installer does detect on `/dev/sda1` existed on that partition before `void-installer` was run.

![void_part_1](https://user-images.githubusercontent.com/24482746/70382794-7d1c1e80-1959-11ea-887c-2f2170914938.jpg)
Initial state.

![void_part_2](https://user-images.githubusercontent.com/24482746/70382797-83aa9600-1959-11ea-95a8-41ec90b78433.jpg)
Selecting `/dev/sda2` for setup.

![void_part_3](https://user-images.githubusercontent.com/24482746/70382798-83aa9600-1959-11ea-8d97-0508bcc70376.jpg)
Choosing to use that as swap space.

![void_part_4](https://user-images.githubusercontent.com/24482746/70382799-83aa9600-1959-11ea-9b84-bb3b7f953a2a.jpg)
Letting the installer create a new swap space on `/dev/sda2`.

![void_part_6](https://user-images.githubusercontent.com/24482746/70382801-84432c80-1959-11ea-8dda-aba889ea91a9.jpg)
Newly created swap space on `/dev/sda2` not recognized by the installer. Moving on to `/dev/sda3`.

![void_part_7](https://user-images.githubusercontent.com/24482746/70382802-84432c80-1959-11ea-948a-c921b6198f04.jpg)
Choosing to use that as an ext3 file system.

![void_part_8](https://user-images.githubusercontent.com/24482746/70382803-84432c80-1959-11ea-9443-e2b03c702205.jpg)
Setting the mount point.

![void_part_9](https://user-images.githubusercontent.com/24482746/70382804-84dbc300-1959-11ea-8492-e998682d7e60.jpg)
Letting the installer create a new ext3 file system on `/dev/sda3`.

![void_part_10](https://user-images.githubusercontent.com/24482746/70382805-84dbc300-1959-11ea-85e4-b3eefc7d75da.jpg)
Newly created ext3 file system on `/dev/sda3` not recognized by the installer.

![void_part_11](https://user-images.githubusercontent.com/24482746/70382806-85745980-1959-11ea-899c-c4dfae307e9d.jpg)
Finding out the installer was acting dumb before and actually recognizes the file systems on those partitions.

**Comment by msiism** [comment]
After playing around with parts of the source code of the latest version of `void-installer` a bit, I used it to reinstall Void on the same machine and figured I had gotten some things wrong in the above.

> There's a bit of a problem with one of the file system setup dialogs in `void-installer`, namely that said dialog doesn't reflect the user's choice of file system for a given partition.

As far as I can see, this is not actually a bug, but rather a design issue. The file system setup dialog generated by `menu_filesystems()` can't reflect the user's choices for the new installation simply because it gets the information it displays by looking up the actual partition and file system layout on the device. And as new file systems aren't written to that device until later in the installation process, it will always display the same information, no matter what the user chooses.

This is, however, not apparent at the time the user selects which file systems to use on the new system and therefore quite confusing. I think it would be much better to have `menu_filesystems()` reflect user choices right away.

**Comment by xtraeme** [comment]
I agree. This is the issue that always has been there for years... but people don't get it. I think the code could be easily modified to reflect user choices.

**Comment by the-maldridge** [comment]
You are correct that this is a design choice of the installer.  More complex use cases should probably be using a [chroot installation](https://docs.voidlinux.org/installation/guides/chroot.html).
